use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Nmap",
        binary: "nmap",
        description: "The network mapper — foundational network discovery, host enumeration, service fingerprinting, OS detection, and vulnerability scanning. Requires root for SYN/UDP scans. The gold standard for network reconnaissance.",
        modes: &[
            Mode {
                name: "Quick Host Discovery",
                cmd_template: r#"nmap -sn -T4 --max-retries 1 --max-rtt-timeout 500ms {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Fast Top Ports",
                cmd_template: r#"nmap -T4 -F --open --min-rate 1000 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Full TCP Port Scan",
                cmd_template: r#"sudo nmap -p- -T4 --open --min-rate 1000 -v {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Service + Script Detection",
                cmd_template: r#"sudo nmap -sS -sV -sC -O --version-intensity 9 --osscan-guess --open -T4 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Aggressive Full Audit",
                cmd_template: r#"sudo nmap -sS -sV -sC -O -A --traceroute --script=banner,http-title,ssl-cert,ssh-hostkey,ftp-anon -T4 --open {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Stealth SYN Scan",
                cmd_template: r#"sudo nmap -sS -T2 -p- --scan-delay 1s --max-retries 2 --open --randomize-hosts {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "UDP Top Ports",
                cmd_template: r#"sudo nmap -sU --top-ports 100 --open -T4 --version-intensity 0 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Full UDP Scan",
                cmd_template: r#"sudo nmap -sU -p- --open -T4 --max-retries 2 --max-rtt-timeout 500ms {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Vulnerability Scan",
                cmd_template: r#"sudo nmap -sS -sV --script=vuln,exploit,auth,default --open -T4 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Custom Script Scan",
                cmd_template: r#"sudo nmap -sS -sV --script={script_name} --open -T4 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Script Name", "script_name")],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "OS Fingerprint",
                cmd_template: r#"sudo nmap -O --osscan-guess --fuzzy --max-os-tries 2 -T4 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "XML Export",
                cmd_template: r#"sudo nmap -sS -sV -sC -O -A --open -T4 {target} -oX {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "Grepable Output",
                cmd_template: r#"sudo nmap -sS -sV --open -T4 {target} -oG {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "gnmap",
            },
            Mode {
                name: "All Formats Export",
                cmd_template: r#"sudo nmap -sS -sV -sC -O -A --open -T4 {target} -oA {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Raw,
                file_ext: "nmap",
            },
            Mode {
                name: "Lethal Full Chain",
                cmd_template: r#"sudo nmap -sn -T4 --max-retries 1 {target} -oN {output_file}.hostup && sudo nmap -sS -p- -T4 --open --min-rate 1000 {target} -oN {output_file}.tcp && sudo nmap -sU --top-ports 100 --open -T4 {target} -oN {output_file}.udp && sudo nmap -sS -sV -sC -O -A --script=vuln,banner,http-title,ssl-cert,ssh-hostkey,ftp-anon --open -T4 {target} -oN {output_file}.full && sudo nmap -sS -sV -A --open -T4 {target} -oX {output_file}.xml && sudo nmap -sS -sV --open -T4 {target} -oG {output_file}.grep"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Raw,
                file_ext: "nmap",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"sudo nmap -p- -T4 --open --min-rate 1000 {target} -oG - | awk '/Host:/{print $2}' | httpx-pd -silent | nuclei -l - -severity critical,high -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "RustScan",
        binary: "rustscan",
        description: "Ultra-fast asynchronous port scanner written in Rust. Scans all 65k ports in seconds, then auto-pipes results into Nmap for service detection. 3x faster than masscan, 10x faster than nmap. Requires root for raw socket scans.",
        modes: &[
            Mode {
                name: "Quick Top Ports",
                cmd_template: r#"rustscan -a {target} --top -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full TCP Port Sweep",
                cmd_template: r#"sudo rustscan -a {target} -p 1-65535 -t 3000 -b 10000 -- -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Nmap Service Pipeline",
                cmd_template: r#"sudo rustscan -a {target} -p 1-65535 -t 3000 -b 10000 -- -sV -sC -O --version-intensity 9 -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Bulk Target Scan",
                cmd_template: r#"rustscan -a {file} -t 3000 -b 10000 -- -Pn -oN {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Stealth Slow Scan",
                cmd_template: r#"rustscan -a {target} -p 1-65535 -t 500 -b 1000 --scan-order random -- -sS -T2 -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "UDP Port Sweep",
                cmd_template: r#"sudo rustscan -a {target} --udp -p 1-65535 -t 3000 -b 5000 -- -sU -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Rate Limited Scan",
                cmd_template: r#"rustscan -a {target} -p 1-65535 -t 1000 -b 5000 -- -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "JSON Machine Output",
                cmd_template: r#"rustscan -a {target} -p 1-65535 -t 3000 -b 10000 --format json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Vulnerability Pipeline",
                cmd_template: r#"sudo rustscan -a {target} -p 1-65535 -t 3000 -b 10000 -- -sV --script=vuln,exploit,auth,banner,http-title,ssl-cert,ssh-hostkey -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Aggressive Full Audit",
                cmd_template: r#"sudo rustscan -a {target} -p 1-65535 -t 3000 -b 10000 -- -sS -sV -sC -O -A --traceroute --version-intensity 9 -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "CIDR Network Sweep",
                cmd_template: r#"sudo rustscan -a {cidr} -p 1-65535 -t 3000 -b 10000 -- -Pn -oN {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr")],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Specific Port Range",
                cmd_template: r#"rustscan -a {target} -p {ports} -t 3000 -b 10000 -- -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Exclude Ports",
                cmd_template: r#"rustscan -a {target} -p 1-65535 --exclude-ports {ports} -t 3000 -b 10000 -- -Pn -oN {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Exclude Ports", "ports")],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "No Nmap Fallback",
                cmd_template: r#"rustscan -a {target} -p 1-65535 -t 3000 -b 10000 --no-nmap -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Lethal Full Chain",
                cmd_template: r#"sudo rustscan -a {target} -p 1-65535 -t 3000 -b 10000 --scan-order random -- -sS -sV -sC -O -A --script=vuln,banner,http-title,ssl-cert,ssh-hostkey,ftp-anon --traceroute --version-intensity 9 -Pn -oN {output_file} && sudo rustscan -a {target} --udp -p 1-65535 -t 3000 -b 5000 -- -sU -Pn -oN {output_file}.udp && rustscan -a {target} -p 1-65535 -t 3000 -b 10000 --format json -o {output_file}.json"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"sudo rustscan -a {target} -p 1-65535 -t 3000 -b 10000 -- -sV -Pn | tee {output_file} | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+' | httpx-pd -silent | nuclei -l - -severity critical,high -json -o {output_file}.nuclei"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
        ],
    },
    Tool {
        name: "Masscan",
        binary: "masscan",
        description: "Internet-scale asynchronous TCP port scanner. Capable of scanning the entire Internet in under 6 minutes. Uses raw sockets, requires root. WARNING: Can overwhelm networks — use with caution and proper rate limits.",
        modes: &[
            Mode {
                name: "Quick CIDR Sweep",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --rate 1000 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Binary Output",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --rate 1000 --wait 0 -oB {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Raw,
                file_ext: "masscan",
            },
            Mode {
                name: "JSON Machine Output",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --rate 1000 --wait 0 -oJ {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "XML Importable",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --rate 1000 --wait 0 -oX {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "Greppable List",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --rate 1000 --wait 0 -oG {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Lines,
                file_ext: "gnmap",
            },
            Mode {
                name: "Resume Interrupted",
                cmd_template: r#"masscan --resume {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Randomized Stealth",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --rate 500 --randomize-hosts --seed 8675309 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Exclude Ranges",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --excludefile {exclude_file} --rate 1000 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports"), InputKind::Custom("Exclude File", "exclude_file")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Top 100 Ports Fast",
                cmd_template: r#"sudo masscan {cidr} --top-ports 100 --rate 10000 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Banner Grab",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --banners --rate 1000 --wait 5 -oJ {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Internet Range",
                cmd_template: r#"sudo masscan 0.0.0.0/0 -p{ports} --excludefile {exclude_file} --rate 100000 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("Ports", "ports"), InputKind::Custom("Exclude File", "exclude_file")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Specific IP Range",
                cmd_template: r#"sudo masscan {ip_range} -p{ports} --rate 1000 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("IP Range", "ip_range"), InputKind::Custom("Ports", "ports")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Adapter Specify",
                cmd_template: r#"sudo masscan {cidr} -p{ports} --adapter {adapter} --router-ip {router_ip} --rate 1000 --wait 0 -oL {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr"), InputKind::Custom("Ports", "ports"), InputKind::Custom("Adapter", "adapter"), InputKind::Custom("Router IP", "router_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Convert Binary to Readable",
                cmd_template: r#"masscan --readscan {output_file} -oL {output_file}.txt"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Lethal Full Chain",
                cmd_template: r#"sudo masscan {cidr} -p1-65535 --rate 10000 --randomize-hosts --wait 0 -oB {output_file}.bin && masscan --readscan {output_file}.bin -oL {output_file}.list && masscan --readscan {output_file}.bin -oJ {output_file}.json && masscan --readscan {output_file}.bin -oG {output_file}.grep && sudo masscan {cidr} -p1-65535 --banners --rate 5000 --wait 5 -oJ {output_file}.banners"#,
                inputs: &[InputKind::Custom("CIDR", "cidr")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
        ],
    },
    Tool {
        name: "Naabu",
        binary: "naabu",
        description: "Fast asynchronous port scanner with SYN/CONNECT stealth, passive port discovery via Shodan/Censys, CDN exclusion, and seamless Nmap integration. Written in Go. Requires root for SYN scans.",
        modes: &[
            Mode {
                name: "Host Discovery",
                cmd_template: r#"naabu -host {target} -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CIDR Network Sweep",
                cmd_template: r#"naabu -host {cidr} -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Custom("CIDR", "cidr")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Top 1000 Ports",
                cmd_template: r#"naabu -host {target} -top-ports 1000 -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Nmap Service Pipeline",
                cmd_template: r#"naabu -host {target} -c 50 -rate 1000 -nmap-cli 'nmap -sV -sC -O --version-intensity 9 -Pn' -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exclude Known Ports",
                cmd_template: r#"naabu -host {target} -exclude-ports {ports} -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Exclude Ports", "ports")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rate Limited Stealth",
                cmd_template: r#"naabu -host {target} -c 10 -rate 100 -timeout 5000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CDN Bypass Scan",
                cmd_template: r#"naabu -host {target} -exclude-cdn -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Machine Output",
                cmd_template: r#"naabu -host {target} -json -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Real-Time Stream",
                cmd_template: r#"naabu -host {target} -stream -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Port + Deep Nmap",
                cmd_template: r#"naabu -host {target} -p - -c 50 -rate 1000 -timeout 30000 -nmap-cli 'nmap -sS -sV -sC -O -A --traceroute --version-intensity 9 -Pn' -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Passive Port Discovery",
                cmd_template: r#"naabu -host {target} -passive -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SYN Stealth Scan",
                cmd_template: r#"sudo naabu -host {target} -p - -scan-type s -c 100 -rate 5000 -timeout 30000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Bulk List Scan",
                cmd_template: r#"naabu -list {file} -c 50 -rate 1000 -top-ports 1000 -o {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Proxy Routed Scan",
                cmd_template: r#"naabu -host {target} -proxy {proxy_url} -c 50 -rate 1000 -o {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Proxy URL", "proxy_url")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Lethal Full Chain",
                cmd_template: r#"naabu -host {target} -p - -c 50 -rate 1000 -timeout 30000 -json -o {output_file}.json && naabu -host {target} -p - -c 50 -rate 1000 -timeout 30000 -nmap-cli 'nmap -sS -sV -sC -O -A --traceroute --version-intensity 9 -Pn' -o {output_file}.nmap && naabu -host {target} -passive -o {output_file}.passive"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"naabu -host {target} -p - -c 50 -rate 1000 -json -o {output_file} && cat {output_file} | jq -r '.host + ":" + (.port | tostring)' | httpx-pd -silent | nuclei -l - -severity critical,high -json -o {output_file}.nuclei"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "HTTPX",
        binary: "httpx",
        description: "Fast, multi-purpose HTTP prober with advanced fingerprinting.",
        modes: &[
            Mode {
                name: "Probe List",
                cmd_template: r#"httpx -l {host_list} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Tech Detect",
                cmd_template: r#"httpx -l {host_list} -tech-detect -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Status Code",
                cmd_template: r#"httpx -l {host_list} -status-code -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Title Grab",
                cmd_template: r#"httpx -l {host_list} -title -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Screenshot",
                cmd_template: r#"httpx -l {host_list} -screenshot -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "Web Server",
                cmd_template: r#"httpx -l {host_list} -web-server -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CDN Detection",
                cmd_template: r#"httpx -l {host_list} -cdn -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Favicon Hash",
                cmd_template: r#"httpx -l {host_list} -favicon -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"httpx -l {host_list} -json -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Recon",
                cmd_template: r#"httpx -l {host_list} -tech-detect -status-code -title -web-server -cdn -json -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "DNSX",
        binary: "dnsx",
        description: "Fast multi-purpose DNS toolkit for DNS enumeration, wildcard filtering, DNSSEC validation, and subdomain resolution. Written in Go. Perfect for filtering valid subdomains and extracting DNS intelligence at scale.",
        modes: &[
            Mode {
                name: "A Record Resolution",
                cmd_template: r#"dnsx -l {domain_list} -a -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AAAA Record Resolution",
                cmd_template: r#"dnsx -l {domain_list} -aaaa -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "MX Record Extraction",
                cmd_template: r#"dnsx -l {domain_list} -mx -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NS Record Enumeration",
                cmd_template: r#"dnsx -l {domain_list} -ns -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "TXT Record Hunt",
                cmd_template: r#"dnsx -l {domain_list} -txt -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CNAME Chain Trace",
                cmd_template: r#"dnsx -l {domain_list} -cname -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PTR Reverse Lookup",
                cmd_template: r#"dnsx -l {ip_list} -ptr -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SOA Record Query",
                cmd_template: r#"dnsx -l {domain_list} -soa -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Wildcard Filter",
                cmd_template: r#"dnsx -l {domain_list} -wd {wildcard_domain} -o {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Wildcard Domain", "wildcard_domain")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full DNS Intelligence",
                cmd_template: r#"dnsx -l {domain_list} -a -aaaa -mx -ns -txt -cname -soa -resp -retry 3 -json -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "DNSSEC Validation",
                cmd_template: r#"dnsx -l {domain_list} -doh -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DoH (DNS over HTTPS)",
                cmd_template: r#"dnsx -l {domain_list} -doh -a -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CDN Detection",
                cmd_template: r#"dnsx -l {domain_list} -cdn -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Raw DNS Query",
                cmd_template: r#"dnsx -l {domain_list} -raw -resp -retry 3 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Lethal DNS Pipeline",
                cmd_template: r#"dnsx -l {domain_list} -a -aaaa -resp -retry 3 -o {output_file}.dns && cat {output_file}.dns | awk '{print $1}' | sort -u | dnsx -l - -cname -mx -ns -txt -soa -resp -retry 3 -json -o {output_file}.full && cat {output_file}.full | jq -r 'select(.a != null) | .host' | httpx-pd -silent -sc -title -tech-detect -o {output_file}.live && cat {output_file}.full | jq -r 'select(.mx != null) | .mx[]' | sort -u > {output_file}.mx_servers && cat {output_file}.full | jq -r 'select(.ns != null) | .ns[]' | sort -u > {output_file}.ns_servers && cat {output_file}.full | jq -r 'select(.txt != null) | .txt[]' | grep -oE '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}' | sort -u > {output_file}.emails"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Subfinder DNS Resolve",
                cmd_template: r#"subfinder -d {domain} -silent | dnsx -a -resp -retry 3 -o {output_file} && cat {output_file} | awk '{print $1}' | httpx-pd -silent -sc -title -o {output_file}.live"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"dnsx -l {domain_list} -a -resp -retry 3 -json -o {output_file} && cat {output_file} | jq -r 'select(.a != null) | .host' | nuclei -l - -severity critical,high -json -o {output_file}.nuclei"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Pipeline to Naabu",
                cmd_template: r#"dnsx -l {domain_list} -a -resp -retry 3 -o {output_file} && cat {output_file} | awk '{print $2}' | sort -u | naabu -list - -p - -c 50 -o {output_file}.ports"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "WhatWeb",
        binary: "whatweb",
        description: "Next-generation web scanner that identifies CMS, blogging platforms, JavaScript libraries, web servers, analytics, and 900+ other technologies. Perfect for technology fingerprinting and version detection.",
        modes: &[
            Mode {
                name: "Single Target",
                cmd_template: r#"whatweb {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Target List",
                cmd_template: r#"whatweb -i {file} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verbose Fingerprint",
                cmd_template: r#"whatweb -v {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Aggressive Level 3",
                cmd_template: r#"whatweb -a 3 {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Colour Output",
                cmd_template: r#"whatweb --colour=always {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Log",
                cmd_template: r#"whatweb --log-json {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "XML Log",
                cmd_template: r#"whatweb --log-xml {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "SQL Database",
                cmd_template: r#"whatweb --log-sql {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Raw,
                file_ext: "db",
            },
            Mode {
                name: "Proxy Routed",
                cmd_template: r#"whatweb --proxy {proxy} {target} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Proxy", "proxy")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Aggressive Scan",
                cmd_template: r#"whatweb -a 3 -v --log-json {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Pipeline from httpx",
                cmd_template: r#"cat {file} | awk '{print $1}' | whatweb -i - -a 3 --log-json {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"whatweb {target} -a 3 | grep -oP 'https?://[^ ]+' | httpx-pd -silent | nuclei -l - -tags tech -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Technology Extraction",
                cmd_template: r#"whatweb {target} -a 3 --log-json {output_file} && cat {output_file} | jq -r '.plugins | keys[]' | sort -u > {output_file}.technologies.txt && cat {output_file} | jq -r '.plugins | to_entries[] | select(.value.version != null) | "\(.key):\(.value.version)"' | sort -u > {output_file}.versions.txt"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Bulk Technology Map",
                cmd_template: r#"whatweb -i {file} -a 3 --log-json {output_file} && cat {output_file} | jq -r '.target' | sort -u > {output_file}.targets.txt && cat {output_file} | jq -r '.plugins | keys[]' | sort | uniq -c | sort -rn > {output_file}.tech_frequency.txt && cat {output_file} | jq -r 'select(.plugins | has("WordPress")) | .target' > {output_file}.wordpress.txt && cat {output_file} | jq -r 'select(.plugins | has("Apache")) | .target' > {output_file}.apache.txt && cat {output_file} | jq -r 'select(.plugins | has("nginx")) | .target' > {output_file}.nginx.txt"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Lethal Tech Chain",
                cmd_template: r#"whatweb {target} -a 3 --log-json {output_file} && cat {output_file} | jq -r '.plugins | to_entries[] | select(.value.version != null) | "\(.key):\(.value.version)"' | sort -u > {output_file}.versions.txt && cat {output_file} | jq -r '.plugins | keys[]' | while read tech; do echo "Searching exploits for $tech"; findsploit "$tech" >> {output_file}.exploits.txt 2>/dev/null; done && cat {output_file} | jq -r '.target' | httpx-pd -silent | nuclei -l - -tags cve,exposure -severity critical,high -json -o {output_file}.nuclei && cat {output_file} | jq -r '.target' | httpx-pd -silent -mc 200 | awk '{print $1}' > /tmp/whatweb_eyewitness.txt && eyewitness --web -f /tmp/whatweb_eyewitness.txt --threads 20 --timeout 15 -d {output_file}.eyewitness"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Cloudlist",
        binary: "cloudlist",
        description: "Multi-cloud asset discovery for AWS, Azure, GCP, DigitalOcean, Linode, and more. Enumerates cloud resources, exposed services, and misconfigurations. Requires cloud provider credentials in ~/.config/cloudlist/provider-config.yaml.",
        modes: &[
            Mode {
                name: "AWS Enumeration",
                cmd_template: r#"cloudlist -provider aws -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Azure Enumeration",
                cmd_template: r#"cloudlist -provider azure -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "GCP Enumeration",
                cmd_template: r#"cloudlist -provider gcp -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DigitalOcean Enumeration",
                cmd_template: r#"cloudlist -provider do -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Linode Enumeration",
                cmd_template: r#"cloudlist -provider linode -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "All Providers",
                cmd_template: r#"cloudlist -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Inventory",
                cmd_template: r#"cloudlist -json -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Host Only",
                cmd_template: r#"cloudlist -host-only -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP Only",
                cmd_template: r#"cloudlist -ip-only -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to Naabu",
                cmd_template: r#"cloudlist -ip-only | sort -u | naabu -list - -c 50 -rate 1000 -top-ports 1000 -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to httpx",
                cmd_template: r#"cloudlist -host-only | sort -u | httpx-pd -silent -sc -title -tech-detect -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"cloudlist -host-only | sort -u | httpx-pd -silent | nuclei -l - -severity critical,high -json -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Pipeline to EyeWitness",
                cmd_template: r#"cloudlist -host-only | sort -u | httpx-pd -silent -mc 200 | awk '{print $1}' > /tmp/cloudlist_urls.txt && eyewitness --web -f /tmp/cloudlist_urls.txt --threads 20 --timeout 15 -d {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Pipeline to WhatWeb",
                cmd_template: r#"cloudlist -host-only | sort -u | httpx-pd -silent | awk '{print $1}' | whatweb -i - -a 3 --log-json {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Lethal Cloud Chain",
                cmd_template: r#"cloudlist -json -o {output_file}.cloudlist && cat {output_file}.cloudlist | jq -r 'select(.ip != null) | .ip' | sort -u | naabu -list - -c 50 -rate 1000 -p - -o {output_file}.naabu && cat {output_file}.cloudlist | jq -r 'select(.host != null) | .host' | sort -u | httpx-pd -silent -sc -title -tech-detect -o {output_file}.httpx && cat {output_file}.httpx | awk '{print $1}' | nuclei -l - -severity critical,high -json -o {output_file}.nuclei && cat {output_file}.httpx | awk '{print $1}' > /tmp/cloudlist_eyewitness.txt && eyewitness --web -f /tmp/cloudlist_eyewitness.txt --threads 20 --timeout 15 -d {output_file}.eyewitness && cat {output_file}.cloudlist | jq -r 'select(.provider != null) | .provider' | sort | uniq -c | sort -rn > {output_file}.provider_stats.txt && cat {output_file}.cloudlist | jq -r 'select(.region != null) | .region' | sort | uniq -c | sort -rn > {output_file}.region_stats.txt && cat {output_file}.cloudlist | jq -r 'select(.service != null) | .service' | sort | uniq -c | sort -rn > {output_file}.service_stats.txt"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Uncover",
        binary: "uncover",
        description: "Discover exposed hosts on the internet using multiple search engine APIs (Shodan, Censys, FOFA, Hunter, Quake). Feeds directly into httpx, naabu, and nuclei for automated exploitation chains. Requires API keys in ~/.config/uncover/provider-config.yaml.",
        modes: &[
            Mode {
                name: "Shodan Hunt",
                cmd_template: r#"uncover -q "{query}" -e shodan -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Censys Hunt",
                cmd_template: r#"uncover -q "{query}" -e censys -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "FOFA Hunt",
                cmd_template: r#"uncover -q "{query}" -e fofa -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hunter Hunt",
                cmd_template: r#"uncover -q "{query}" -e hunter -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Quake Hunt",
                cmd_template: r#"uncover -q "{query}" -e quake -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multi-Engine Blast",
                cmd_template: r#"uncover -q "{query}" -e shodan,censys,fofa,quake -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Intelligence",
                cmd_template: r#"uncover -q "{query}" -e shodan,censys -json -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Limited Results",
                cmd_template: r#"uncover -q "{query}" -e shodan -l {limit} -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query"), InputKind::Custom("Limit", "limit")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP Extraction",
                cmd_template: r#"uncover -q "{query}" -e shodan -field ip -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Host:Port Extraction",
                cmd_template: r#"uncover -q "{query}" -e shodan -field ip:port -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to httpx",
                cmd_template: r#"uncover -q "{query}" -e shodan -field ip:port | httpx-pd -silent -sc -title -tech-detect -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"uncover -q "{query}" -e shodan,censys -field ip:port | httpx-pd -silent | nuclei -l - -severity critical,high -json -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Pipeline to Naabu",
                cmd_template: r#"uncover -q "{query}" -e shodan -field ip | sort -u | naabu -list - -c 50 -rate 1000 -top-ports 1000 -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to EyeWitness",
                cmd_template: r#"uncover -q "{query}" -e shodan -field ip:port | httpx-pd -silent -mc 200 | awk '{print $1}' > /tmp/uncover_urls.txt && eyewitness --web -f /tmp/uncover_urls.txt --threads 20 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Lethal Full Chain",
                cmd_template: r#"uncover -q "{query}" -e shodan,censys,fofa,quake -json -o {output_file}.uncover && cat {output_file}.uncover | jq -r 'select(.ip != null) | .ip' | sort -u | naabu -list - -c 50 -rate 1000 -p - -o {output_file}.naabu && cat {output_file}.naabu | httpx-pd -silent -sc -title -tech-detect -o {output_file}.httpx && cat {output_file}.httpx | awk '{print $1}' | nuclei -l - -severity critical,high -json -o {output_file}.nuclei && cat {output_file}.httpx | awk '{print $1}' > /tmp/uncover_eyewitness.txt && eyewitness --web -f /tmp/uncover_eyewitness.txt --threads 20 --timeout 15 -d {output_file}.eyewitness && cat {output_file}.uncover | jq -r 'select(.hostnames != null) | .hostnames[]' | sort -u > {output_file}.hostnames.txt && cat {output_file}.uncover | jq -r 'select(.location != null) | [.ip, .location.city, .location.country] | @tsv' | sort -u > {output_file}.geolocation.txt"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "EyeWitness",
        binary: "eyewitness",
        description: "Visual reconnaissance tool that captures screenshots of web applications, RDP sessions, and VNC servers. Identifies default credentials, technology stacks, and exposed admin panels from visual evidence. Python/Selenium based.",
        modes: &[
            Mode {
                name: "Web Screenshot Bulk",
                cmd_template: r#"eyewitness --web -f {file} --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Single URL Capture",
                cmd_template: r#"eyewitness --web --single {url} --timeout 15 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" -d {output_file}"#,
                inputs: &[InputKind::Url],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "RDP Session Capture",
                cmd_template: r#"eyewitness --rdp -f {file} --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "VNC Session Capture",
                cmd_template: r#"eyewitness --vnc -f {file} --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "All Protocols Sweep",
                cmd_template: r#"eyewitness --web --rdp --vnc -f {file} --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Proxy Routed Capture",
                cmd_template: r#"eyewitness --web -f {file} --proxy-ip {proxy_ip} --proxy-port {proxy_port} --threads 5 --timeout 20 -d {output_file}"#,
                inputs: &[InputKind::File, InputKind::Custom("Proxy IP", "proxy_ip"), InputKind::Custom("Proxy Port", "proxy_port")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "No DNS Resolution",
                cmd_template: r#"eyewitness --web -f {file} --no-dns --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Custom Timeout",
                cmd_template: r#"eyewitness --web -f {file} --timeout {seconds} --threads 10 -d {output_file}"#,
                inputs: &[InputKind::File, InputKind::Custom("Seconds", "seconds")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Custom User Agent",
                cmd_template: r#"eyewitness --web -f {file} --user-agent "{ua}" --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File, InputKind::Custom("User Agent", "ua")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Mobile User Agent",
                cmd_template: r#"eyewitness --web -f {file} --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1" --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Headless Chrome",
                cmd_template: r#"eyewitness --web -f {file} --headless --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Resolve Hosts First",
                cmd_template: r#"eyewitness --web -f {file} --resolve --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "SSL Certificate Capture",
                cmd_template: r#"eyewitness --web -f {file} --add-http-ports 443,8443 --threads 10 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Credential Detection",
                cmd_template: r#"eyewitness --web -f {file} --threads 10 --timeout 15 --results 100 -d {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Lethal Visual Recon",
                cmd_template: r#"eyewitness --web -f {file} --threads 20 --timeout 15 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" --headless --resolve --results 100 -d {output_file} && eyewitness --rdp -f {file} --timeout 15 -d {output_file}.rdp && eyewitness --vnc -f {file} --timeout 15 -d {output_file}.vnc && cat {output_file}/report.html | grep -oP 'title>\K[^<]+' | sort -u > {output_file}.titles.txt && cat {output_file}/report.html | grep -oP 'basic_creds.*?\K[^<]+' | sort -u > {output_file}.creds.txt && ls {output_file}/screens/ | wc -l > {output_file}.count.txt"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Subfinder Visual Pipeline",
                cmd_template: r#"subfinder -d {domain} -silent | httpx-pd -silent -sc -mc 200 | awk '{print $1}' > {output_file}.urls && eyewitness --web -f {output_file}.urls --threads 20 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Naabu Port Visual Pipeline",
                cmd_template: r#"naabu -host {target} -silent | awk '{print $1":"$2}' | httpx-pd -silent > {output_file}.urls && eyewitness --web -f {output_file}.urls --threads 20 --timeout 15 -d {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Pipeline to Nuclei",
                cmd_template: r#"eyewitness --web -f {file} --threads 20 --timeout 15 -d {output_file} && cat {output_file}/report.html | grep -oP 'href="\K[^"]+' | sed 's/.*\/\///' | nuclei -l - -severity critical,high -json -o {output_file}.nuclei"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
        ],
    },
];
