use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Aircrack-ng",
        binary: "airmon-ng",
        description: "Complete suite for Wi-Fi network security assessment.",
        modes: &[
            Mode {
                name: "Monitor Mode",
                cmd_template: r#"airmon-ng start {interface} > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Network Scan",
                cmd_template: r#"airodump-ng {interface_mon} --write {output_file}"#,
                inputs: &[InputKind::Custom("Interface Mon", "interface_mon")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Targeted Capture",
                cmd_template: r#"airodump-ng -c {channel} --bssid {bssid} -w {output_file} {interface_mon}"#,
                inputs: &[InputKind::Custom("Channel", "channel"), InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Interface Mon", "interface_mon")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Deauth Attack",
                cmd_template: r#"aireplay-ng -0 {count} -a {bssid} -c {client_mac} {interface_mon} > {output_file}"#,
                inputs: &[InputKind::Custom("Count", "count"), InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Client Mac", "client_mac"), InputKind::Custom("Interface Mon", "interface_mon")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WPA Cracking",
                cmd_template: r#"aircrack-ng -w {wordlist} -b {bssid} {output_file} > {output_file}"#,
                inputs: &[InputKind::Wordlist, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WEP Injection",
                cmd_template: r#"aireplay-ng -3 -b {bssid} -h {mac} {interface_mon} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Mac", "mac"), InputKind::Custom("Interface Mon", "interface_mon")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Fake Auth",
                cmd_template: r#"aireplay-ng -1 0 -a {bssid} -h {mac} {interface_mon} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Mac", "mac"), InputKind::Custom("Interface Mon", "interface_mon")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Packet Forge",
                cmd_template: r#"packetforge-ng -0 -a {bssid} -h {mac} -k {ip_dst} -l {ip_src} -y {prga} -w {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Mac", "mac"), InputKind::Custom("Ip Dst", "ip_dst"), InputKind::Custom("Ip Src", "ip_src"), InputKind::Custom("Prga", "prga")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "PMKID Capture",
                cmd_template: r#"hcxdumptool -i {interface} -o {output_file} --enable_status=1"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Full WPA Audit",
                cmd_template: r#"airmon-ng start {iface} && airodump-ng -c {ch} --bssid {bssid} -w {output_file} {iface_mon} & aireplay-ng -0 10 -a {bssid} -c {client} {iface_mon}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Ch", "ch"), InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Iface Mon", "iface_mon"), InputKind::Custom("Client", "client")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
    Tool {
        name: "Wifite2",
        binary: "wifite",
        description: "Automated wireless attack tool for WEP, WPA, and WPS.",
        modes: &[
            Mode {
                name: "Auto Attack",
                cmd_template: r#"wifite --kill --cracked > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WPA Only",
                cmd_template: r#"wifite -i {interface} --wpa --dict {wordlist} > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WPS Attack",
                cmd_template: r#"wifite -i {interface} --wps --pixie > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PMKID Only",
                cmd_template: r#"wifite -i {interface} --pmkid --dict {wordlist} > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Dict",
                cmd_template: r#"wifite -i {interface} --dict {wordlist} > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Channel Filter",
                cmd_template: r#"wifite -i {interface} -c 1,6,11 > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Power Filter",
                cmd_template: r#"wifite -i {interface} --pow 50 > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Cracked Check",
                cmd_template: r#"wifite --cracked > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Handshake Verify",
                cmd_template: r#"wifite --check {capture_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Capture File", "capture_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Assessment",
                cmd_template: r#"wifite --kill --wpa --wps --pmkid --dict {wordlist} -p 30 > {output_file}"#,
                inputs: &[InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "hcxtools",
        binary: "hcxdumptool",
        description: "WLAN attack and capture tools for PMKID and handshake cracking.",
        modes: &[
            Mode {
                name: "PMKID Capture",
                cmd_template: r#"hcxdumptool -i {interface} -o {output_file} --enable_status=15"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Convert Hashcat",
                cmd_template: r#"hcxpcapngtool -o {output_file} -E {output_file} {capture}.pcapng"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "22000",
            },
            Mode {
                name: "Filter BSSID",
                cmd_template: r#"hcxpcapngtool -o {output_file} --filtermode=2 --filterlist={bssid_file} {capture}"#,
                inputs: &[InputKind::Custom("Bssid File", "bssid_file"), InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "22000",
            },
            Mode {
                name: "MAC Filter",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --filterlist_ap={mac_file} --filtermode=2"#,
                inputs: &[InputKind::Interface, InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Client-less",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --enable_status=1 --active_beacon"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Channel Assessment",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --do_rcascan"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "GPS Logging",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --use_gpsd=localhost:2947"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Hash Info",
                cmd_template: r#"hcxhashtool -i {hash}.22000 --info=stdout > {output_file}"#,
                inputs: &[InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "ESSID Extract",
                cmd_template: r#"hcxpcapngtool -o {hash}.22000 -E {output_file} --essid=stdout {capture} > {output_file}"#,
                inputs: &[InputKind::Hash, InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Pipeline",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --enable_status=15 --active_beacon --channel=1,6,11 && hcxpcapngtool -o {output_file} {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "22000",
            },
        ],
    },
    Tool {
        name: "hashcat (Wi-Fi Modes)",
        binary: "hashcat",
        description: "GPU-accelerated Wi-Fi password cracking.",
        modes: &[
            Mode {
                name: "WPA2 Crack",
                cmd_template: r#"hashcat -m 2500 -a 0 {capture}.hccapx {wordlist} -o {output_file}"#,
                inputs: &[InputKind::File, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PMKID Crack",
                cmd_template: r#"hashcat -m 22000 -a 0 {hash}.22000 {wordlist} -o {output_file}"#,
                inputs: &[InputKind::Hash, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Mask Attack",
                cmd_template: r#"hashcat -m 22000 -a 3 {hash}.22000 '?u?l?l?l?l?d?d?d?d' -o {output_file}"#,
                inputs: &[InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rules Attack",
                cmd_template: r#"hashcat -m 22000 -a 0 {hash}.22000 {wordlist} -r {rules} -o {output_file}"#,
                inputs: &[InputKind::Hash, InputKind::Wordlist, InputKind::Custom("Rules", "rules")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Brute Force",
                cmd_template: r#"hashcat -m 22000 -a 3 {hash}.22000 '?a?a?a?a?a?a?a?a' -o {output_file}"#,
                inputs: &[InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Session Save",
                cmd_template: r#"hashcat -m 22000 -a 0 {hash}.22000 {wordlist} -o {output_file} --session={name}"#,
                inputs: &[InputKind::Hash, InputKind::Wordlist, InputKind::Custom("Name", "name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Show Cracked",
                cmd_template: r#"hashcat -m 22000 {hash}.22000 --show > {output_file}"#,
                inputs: &[InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Benchmark",
                cmd_template: r#"hashcat -m 22000 -b > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multi Wordlist",
                cmd_template: r#"hashcat -m 22000 -a 0 {hash}.22000 {wordlist1} {wordlist2} -o {output_file}"#,
                inputs: &[InputKind::Hash, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Optimized Crack",
                cmd_template: r#"hashcat -m 22000 -a 0 {hash}.22000 {wordlist} -O -w 3 -o {output_file}"#,
                inputs: &[InputKind::Hash, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Reaver",
        binary: "reaver",
        description: "WPS PIN brute-forcing to recover WPA/WPA2 passphrases.",
        modes: &[
            Mode {
                name: "Basic Attack",
                cmd_template: r#"reaver -i {interface} -b {bssid} -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Channel Lock",
                cmd_template: r#"reaver -i {interface} -b {bssid} -c {channel} -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rate Limit",
                cmd_template: r#"reaver -i {interface} -b {bssid} -d 5 -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom PIN",
                cmd_template: r#"reaver -i {interface} -b {bssid} -p {pin} -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Pin", "pin")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "MAC Spoof",
                cmd_template: r#"reaver -i {interface} -b {bssid} -vv -N -n > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Timeout",
                cmd_template: r#"reaver -i {interface} -b {bssid} -t 30 -x 60 -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Session Resume",
                cmd_template: r#"reaver -i {interface} -b {bssid} -s {session_file} -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Session File", "session_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Ignore Locks",
                cmd_template: r#"reaver -i {interface} -b {bssid} -L -vv > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pixie Dust",
                cmd_template: r#"reaver -i {interface} -b {bssid} -vv -K 1 > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full WPS",
                cmd_template: r#"reaver -i {interface} -b {bssid} -c {ch} -vv -K 1 -t 30 -d 5 -L > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Ch", "ch")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Bully",
        binary: "bully",
        description: "Modern, efficient WPS brute-forcing tool.",
        modes: &[
            Mode {
                name: "Basic Attack",
                cmd_template: r#"bully -b {bssid} -c {channel} {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verbose",
                cmd_template: r#"bully -b {bssid} -c {channel} -v 3 {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Force Mode",
                cmd_template: r#"bully -b {bssid} -c {channel} -F {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom PIN",
                cmd_template: r#"bully -b {bssid} -c {channel} -p {pin} {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Custom("Pin", "pin"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Session Restore",
                cmd_template: r#"bully -b {bssid} -s {session_file} {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Session File", "session_file"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Brute Force",
                cmd_template: r#"bully -b {bssid} -c {channel} -B {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "No Random MAC",
                cmd_template: r#"bully -b {bssid} -c {channel} -R {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Wireless Retry",
                cmd_template: r#"bully -b {bssid} -c {channel} -r {retries} {interface} > {output_file}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Custom("Retries", "retries"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Detect Mode",
                cmd_template: r#"bully -b {bssid} -c {channel} -o {output_file} {interface}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Attack",
                cmd_template: r#"bully -b {bssid} -c {channel} -v 3 -F -B -o {output_file} {interface}"#,
                inputs: &[InputKind::Custom("Bssid", "bssid"), InputKind::Custom("Channel", "channel"), InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Bettercap (Wireless)",
        binary: "bettercap",
        description: "Network attack and monitoring framework with wireless capabilities.",
        modes: &[
            Mode {
                name: "WiFi Scan",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; wifi.show' > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PMKID Capture",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; wifi.assoc {bssid}' > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Deauth Attack",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; wifi.deauth {bssid}' > {output_file}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Handshake Capture",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; set wifi.handshakes.file {output_file} > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "BLE Scan",
                cmd_template: r#"bettercap -eval 'ble.recon on; ble.show' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "HID Injection",
                cmd_template: r#"bettercap -eval 'hid.inject {script}' > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "MouseJack",
                cmd_template: r#"bettercap -eval 'hid.scan; hid.sniff; hid.inject {script}' > {output_file}"#,
                inputs: &[InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Channel Hop",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; wifi.channel 1,6,11' > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Save Capture",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; set wifi.handshakes.file {output_file} > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Assessment",
                cmd_template: r#"bettercap -iface {interface} -eval 'wifi.recon on; wifi.channel 1,6,11; wifi.assoc all; set wifi.handshakes.file {output_file} > {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "hostapd-wpe",
        binary: "hostapd-wpe",
        description: "Rogue access point for enterprise wireless attacks.",
        modes: &[
            Mode {
                name: "Rogue AP",
                cmd_template: r#"hostapd-wpe {config_file} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "SSID Spoof",
                cmd_template: r#"sed -i 's/^ssid=.*/ssid={target_ssid}/' /etc/hostapd-wpe/hostapd-wpe.conf && hostapd-wpe /etc/hostapd-wpe/hostapd-wpe.conf > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ssid", "target_ssid")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Channel Setup",
                cmd_template: r#"hostapd-wpe -c {channel} {config_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Channel", "channel"), InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "KARMA Mode",
                cmd_template: r#"hostapd-wpe --karma {config_file} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "EAP Mode",
                cmd_template: r#"hostapd-wpe --eap {config_file} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Log Output",
                cmd_template: r#"hostapd-wpe -o {output_file} {config_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Certificate Config",
                cmd_template: r#"hostapd-wpe --cert {cert_file} --key {key_file} {config} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Broadcast SSID",
                cmd_template: r#"hostapd-wpe --broadcast {config_file} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Hash Analysis",
                cmd_template: r#"cat {log_file} | grep 'jnettop' | asleap -C {challenge} -R {response} -W {wordlist} > {output_file}"#,
                inputs: &[InputKind::Custom("Log File", "log_file"), InputKind::Custom("Challenge", "challenge"), InputKind::Custom("Response", "response"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Enterprise",
                cmd_template: r#"hostapd-wpe --karma --eap -o {output_file} {config} && asleap -C {chall} -R {resp} -W {wordlist} > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Custom("Chall", "chall"), InputKind::Custom("Resp", "resp"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "asleap",
        binary: "asleap",
        description: "LEAP and MS-CHAPv2 wireless authentication password recovery.",
        modes: &[
            Mode {
                name: "Basic Crack",
                cmd_template: r#"asleap -C {challenge} -R {response} -W {wordlist} > {output_file}"#,
                inputs: &[InputKind::Custom("Challenge", "challenge"), InputKind::Custom("Response", "response"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Generate Table",
                cmd_template: r#"asleap -G -W {wordlist} -D {output_file} > {output_file}"#,
                inputs: &[InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Table Lookup",
                cmd_template: r#"asleap -C {challenge} -R {response} -D {output_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Challenge", "challenge"), InputKind::Custom("Response", "response")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pcap Extract",
                cmd_template: r#"asleap -r {capture}.pcap -W {wordlist} > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSID Filter",
                cmd_template: r#"asleap -r {capture}.pcap -W {wordlist} -S {ssid} > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Wordlist, InputKind::Custom("Ssid", "ssid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LEAP Attack",
                cmd_template: r#"asleap -C {challenge} -R {response} -W {wordlist} -L > {output_file}"#,
                inputs: &[InputKind::Custom("Challenge", "challenge"), InputKind::Custom("Response", "response"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verbose",
                cmd_template: r#"asleap -C {challenge} -R {response} -W {wordlist} -v > {output_file}"#,
                inputs: &[InputKind::Custom("Challenge", "challenge"), InputKind::Custom("Response", "response"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multiple Wordlists",
                cmd_template: r#"asleap -C {challenge} -R {response} -W {wordlist1} -W {wordlist2} > {output_file}"#,
                inputs: &[InputKind::Custom("Challenge", "challenge"), InputKind::Custom("Response", "response"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pcap Batch",
                cmd_template: r#"asleap -r {capture}.pcap -W {wordlist} -o {output_file}"#,
                inputs: &[InputKind::File, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Pipeline",
                cmd_template: r#"asleap -r {capture}.pcap -W {wordlist} -D {precomputed} -o {output_file} -v"#,
                inputs: &[InputKind::File, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "hcxdumptool",
        binary: "hcxdumptool",
        description: "Packet capture from WLAN devices for hashcat cracking.",
        modes: &[
            Mode {
                name: "Basic Capture",
                cmd_template: r#"hcxdumptool -i {interface} -o {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Status Display",
                cmd_template: r#"hcxdumptool -i {interface} -o {output_file} --enable_status=15"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "AP Filter",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --filterlist_ap={mac_file} --filtermode=2"#,
                inputs: &[InputKind::Interface, InputKind::File],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Active Beacon",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --active_beacon"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Client Deauth",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --enable_status=15 --bpfc={bssid}"#,
                inputs: &[InputKind::Interface, InputKind::Custom("Bssid", "bssid")],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Channel List",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --channel=1,6,11"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Channel Assessment",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --do_rcascan"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Extended Status",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --enable_status=63"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "GPS Tracking",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --use_gpsd=localhost:2947"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "pcapng",
            },
            Mode {
                name: "Full Assessment",
                cmd_template: r#"hcxdumptool -i {iface} -o {output_file} --enable_status=15 --active_beacon --channel=1,6,11 && hcxpcapngtool -o {output_file} {output_file}"#,
                inputs: &[InputKind::Interface],
                output_format: OutputFormat::Raw,
                file_ext: "22000",
            },
        ],
    },
];
