use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Nmap",
        binary: "nmap",
        description: "The network mapper — the foundation of network discovery and security auditing.",
        modes: &[
            Mode {
                name: "Quick Scan",
                cmd_template: r#"nmap -T4 -F {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Full Port Scan",
                cmd_template: r#"nmap -p- -T4 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Service Detection",
                cmd_template: r#"nmap -sV -sC -O {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Aggressive Scan",
                cmd_template: r#"nmap -A -T4 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "UDP Scan",
                cmd_template: r#"nmap -sU -T4 --top-ports 100 {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Script Scan",
                cmd_template: r#"nmap --script={script_name} {target} -oN {output_file}"#,
                inputs: &[InputKind::Custom("Script Name", "script_name"), InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Stealth Scan",
                cmd_template: r#"nmap -sS -T2 -p- {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "OS Detection",
                cmd_template: r#"nmap -O --osscan-guess {target} -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "XML Output",
                cmd_template: r#"nmap -A -T4 {target} -oX {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "Full Audit",
                cmd_template: r#"nmap -sS -sV -sC -O -A -p- -T4 {target} -oA {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
        ],
    },
    Tool {
        name: "RustScan",
        binary: "rustscan",
        description: "Ultra-fast port scanner that feeds results directly into Nmap.",
        modes: &[
            Mode {
                name: "Quick Scan",
                cmd_template: r#"rustscan -a {target} -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "All Ports",
                cmd_template: r#"rustscan -a {target} -p 1-65535 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Nmap Pipeline",
                cmd_template: r#"rustscan -a {target} -- -sV -sC -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Batch Scan",
                cmd_template: r#"rustscan -a {target1},{target2},{target3} -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Scripts",
                cmd_template: r#"rustscan -a {target} --scripts none -- -sV -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
            Mode {
                name: "Top Ports",
                cmd_template: r#"rustscan -a {target} --top -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "UDP Scan",
                cmd_template: r#"rustscan -a {target} -u 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rate Limit",
                cmd_template: r#"rustscan -a {target} -b 500 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"rustscan -a {target} --format json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Pipeline",
                cmd_template: r#"rustscan -a {target} -p 1-65535 -- -sV -sC -O -A -oN {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Nmap,
                file_ext: "nmap",
            },
        ],
    },
    Tool {
        name: "Masscan",
        binary: "masscan",
        description: "Internet-scale port scanner for large network ranges.",
        modes: &[
            Mode {
                name: "Quick CIDR Scan",
                cmd_template: r#"masscan {cidr} -p{ports} --rate 1000 -oB {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "List Output",
                cmd_template: r#"masscan {cidr} -p{ports} --rate 1000 -oL {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"masscan {cidr} -p{ports} --rate 1000 -oJ {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "XML Output",
                cmd_template: r#"masscan {cidr} -p{ports} --rate 1000 -oX {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "Resume Scan",
                cmd_template: r#"masscan --resume {output_file} -oL {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Randomize",
                cmd_template: r#"masscan {cidr} -p{ports} --rate 1000 --randomize-hosts -oL {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Excludefile",
                cmd_template: r#"masscan {cidr} -p{ports} --excludefile {exclude_file} --rate 1000 -oL {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports, InputKind::Custom("Exclude File", "exclude_file")],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Top 100 Ports",
                cmd_template: r#"masscan {cidr} --top-ports 100 --rate 1000 -oL {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
            Mode {
                name: "Banner Grab",
                cmd_template: r#"masscan {cidr} -p{ports} --banners --rate 1000 -oJ {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Ports],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Range Scan",
                cmd_template: r#"masscan {cidr} -p1-65535 --rate 10000 -oL {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "list",
            },
        ],
    },
    Tool {
        name: "Naabu",
        binary: "naabu",
        description: "Fast port scanner with host discovery and Nmap integration.",
        modes: &[
            Mode {
                name: "Host Scan",
                cmd_template: r#"naabu -host {target} -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CIDR Scan",
                cmd_template: r#"naabu -host {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Top Ports",
                cmd_template: r#"naabu -host {target} -top-ports 1000 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Nmap Integration",
                cmd_template: r#"naabu -host {target} -nmap-cli 'nmap -sV -sC' -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exclude Ports",
                cmd_template: r#"naabu -host {target} -exclude-ports 80,443 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rate Limit",
                cmd_template: r#"naabu -host {target} -rate 500 -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CDN Exclusion",
                cmd_template: r#"naabu -host {target} -exclude-cdn -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"naabu -host {target} -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Stream Output",
                cmd_template: r#"naabu -host {target} -stream -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Port + Nmap",
                cmd_template: r#"naabu -host {target} -p - -nmap-cli 'nmap -sV -sC -O -A' -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "HTTPX",
        binary: "httpx",
        description: "Fast, multi-purpose HTTP prober with advanced fingerprinting.",
        modes: &[
            Mode {
                name: "Probe List",
                cmd_template: r#"httpx -l {host_list} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Tech Detect",
                cmd_template: r#"httpx -l {host_list} -tech-detect -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Status Code",
                cmd_template: r#"httpx -l {host_list} -status-code -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Title Grab",
                cmd_template: r#"httpx -l {host_list} -title -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Screenshot",
                cmd_template: r#"httpx -l {host_list} -screenshot -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "Web Server",
                cmd_template: r#"httpx -l {host_list} -web-server -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CDN Detection",
                cmd_template: r#"httpx -l {host_list} -cdn -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Favicon Hash",
                cmd_template: r#"httpx -l {host_list} -favicon -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"httpx -l {host_list} -json -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Recon",
                cmd_template: r#"httpx -l {host_list} -tech-detect -status-code -title -web-server -cdn -json -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "DNSX",
        binary: "dnsx",
        description: "Fast, multi-purpose DNS toolkit for DNS enumeration and verification.",
        modes: &[
            Mode {
                name: "A Record",
                cmd_template: r#"dnsx -l {domain_list} -a -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AAAA Record",
                cmd_template: r#"dnsx -l {domain_list} -aaaa -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "MX Record",
                cmd_template: r#"dnsx -l {domain_list} -mx -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NS Record",
                cmd_template: r#"dnsx -l {domain_list} -ns -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "TXT Record",
                cmd_template: r#"dnsx -l {domain_list} -txt -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CNAME",
                cmd_template: r#"dnsx -l {domain_list} -cname -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PTR (Reverse)",
                cmd_template: r#"dnsx -l {ip_list} -ptr -resp -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SOA",
                cmd_template: r#"dnsx -l {domain_list} -soa -resp -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DNS Wildcard",
                cmd_template: r#"dnsx -l {domain_list} -wd {wildcard_domain} -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full DNS Enum",
                cmd_template: r#"dnsx -l {domain_list} -a -aaaa -mx -ns -txt -cname -soa -json -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "WhatWeb",
        binary: "whatweb",
        description: "Next-generation web scanner for technology fingerprinting.",
        modes: &[
            Mode {
                name: "Single Target",
                cmd_template: r#"whatweb {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Target List",
                cmd_template: r#"whatweb -i {url_list} > {output_file}"#,
                inputs: &[InputKind::Url],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verbose",
                cmd_template: r#"whatweb -v {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Aggression Level 3",
                cmd_template: r#"whatweb -a 3 {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Colour Output",
                cmd_template: r#"whatweb --colour=always {target} > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Log JSON",
                cmd_template: r#"whatweb --log-json {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Log XML",
                cmd_template: r#"whatweb --log-xml {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "Log SQL",
                cmd_template: r#"whatweb --log-sql {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Raw,
                file_ext: "db",
            },
            Mode {
                name: "Proxy",
                cmd_template: r#"whatweb --proxy {proxy} {target} > {output_file}"#,
                inputs: &[InputKind::Custom("Proxy", "proxy"), InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Scan",
                cmd_template: r#"whatweb -a 3 -v --log-json {output_file} {target}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Cloudlist",
        binary: "cloudlist",
        description: "Multi-cloud asset discovery tool for AWS, Azure, GCP, and more.",
        modes: &[
            Mode {
                name: "AWS Scan",
                cmd_template: r#"cloudlist -provider aws -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Azure Scan",
                cmd_template: r#"cloudlist -provider azure -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "GCP Scan",
                cmd_template: r#"cloudlist -provider gcp -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DO Scan",
                cmd_template: r#"cloudlist -provider do -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Linode Scan",
                cmd_template: r#"cloudlist -provider linode -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "All Providers",
                cmd_template: r#"cloudlist -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"cloudlist -json -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Host Only",
                cmd_template: r#"cloudlist -host-only -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP Only",
                cmd_template: r#"cloudlist -ip-only -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Inventory",
                cmd_template: r#"cloudlist -json -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Uncover",
        binary: "uncover",
        description: "Quickly discover exposed hosts on the internet using search engine APIs.",
        modes: &[
            Mode {
                name: "Shodan Query",
                cmd_template: r#"uncover -q "{query}" -e shodan -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Censys Query",
                cmd_template: r#"uncover -q "{query}" -e censys -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "FOFA Query",
                cmd_template: r#"uncover -q "{query}" -e fofa -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hunter Query",
                cmd_template: r#"uncover -q "{query}" -e hunter -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Quake Query",
                cmd_template: r#"uncover -q "{query}" -e quake -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multiple Engines",
                cmd_template: r#"uncover -q "{query}" -e shodan,censys,fofa -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"uncover -q "{query}" -e shodan -json -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Limit Results",
                cmd_template: r#"uncover -q "{query}" -e shodan -l {limit} -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query"), InputKind::Custom("Limit", "limit")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP Only",
                cmd_template: r#"uncover -q "{query}" -e shodan -field ip -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Discovery",
                cmd_template: r#"uncover -q "{query}" -e shodan,censys,fofa,hunter -json -o {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "EyeWitness",
        binary: "eyewitness",
        description: "Take screenshots of websites and identify default credentials.",
        modes: &[
            Mode {
                name: "Web Screenshot",
                cmd_template: r#"eyewitness --web -f {url_list} -d {output_file}"#,
                inputs: &[InputKind::Url],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Single URL",
                cmd_template: r#"eyewitness --web --single {url} -d {output_file}"#,
                inputs: &[InputKind::Url],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "RDP Screenshot",
                cmd_template: r#"eyewitness --rdp -f {ip_list} -d {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "VNC Screenshot",
                cmd_template: r#"eyewitness --vnc -f {ip_list} -d {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "All Protocols",
                cmd_template: r#"eyewitness --web --rdp --vnc -f {ip_list} -d {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Proxy",
                cmd_template: r#"eyewitness --web -f {url_list} --proxy-ip {proxy_ip} --proxy-port {proxy_port} -d {output_file}"#,
                inputs: &[InputKind::Url, InputKind::Custom("Proxy Ip", "proxy_ip"), InputKind::Custom("Proxy Port", "proxy_port")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "No DNS",
                cmd_template: r#"eyewitness --web -f {url_list} --no-dns -d {output_file}"#,
                inputs: &[InputKind::Url],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Timeout Adjust",
                cmd_template: r#"eyewitness --web -f {url_list} --timeout {seconds} -d {output_file}"#,
                inputs: &[InputKind::Url, InputKind::Custom("Seconds", "seconds")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "User Agent",
                cmd_template: r#"eyewitness --web -f {url_list} --user-agent "{ua}" -d {output_file}"#,
                inputs: &[InputKind::Url, InputKind::Custom("Ua", "ua")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Full Web Capture",
                cmd_template: r#"eyewitness --web --rdp --vnc -f {ip_list} --all-protocols --timeout 30 -d {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
        ],
    },
];
