use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Subfinder",
        binary: "subfinder",
        description: "Rapid passive subdomain discovery using multiple online sources.",
        modes: &[
            Mode {
                name: "Passive Subdomain Enum",
                cmd_template: r#"subfinder -d {domain} -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "All Sources Enum",
                cmd_template: r#"subfinder -d {domain} -all -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Recursive Subdomain Enum",
                cmd_template: r#"subfinder -d {domain} -recursive -all -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Active + Wildcard Filter",
                cmd_template: r#"subfinder -d {domain} -all -nW -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Specific Sources Enum",
                cmd_template: r#"subfinder -d {domain} -sources crtsh,virustotal,bufferover,threatcrowd,hackertarget,rapiddns,alienvault,urlscan,chaos,sublist3r,threatminer,dnsdumpster,riddler,pastebin,sitedossier,archive,commoncrawl -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Source Collection JSON",
                cmd_template: r#"subfinder -d {domain} -all -oJ -cs -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Exclude Sources Enum",
                cmd_template: r#"subfinder -d {domain} -all -es {source} -silent -o {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Source", "source")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP Resolution Output",
                cmd_template: r#"subfinder -d {domain} -all -nW -oI -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Bulk Domain Scan",
                cmd_template: r#"subfinder -dL {file} -all -silent -o {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to HTTPX",
                cmd_template: r#"subfinder -d {domain} -sources crtsh,virustotal,bufferover,threatcrowd,hackertarget,rapiddns,alienvault,urlscan,chaos,sublist3r,threatminer,dnsdumpster,riddler,pastebin,sitedossier,archive,commoncrawl -all -recursive -t 100 -timeout 30 -max-time 10 -nW -silent | httpx-pd -silent -sc -title -tech-detect -server -ip -cdn -location -jarm -method -websocket -fc 404,502,503 -mc 200,301,302,401,403,407 -retries 2 -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Amass",
        binary: "amass",
        description: "Comprehensive DNS enumeration and network mapping with deep correlation. Guaranteed output via OAM database query.",
        modes: &[
            Mode {
                name: "Passive Enumeration",
                cmd_template: r#"amass enum -passive -d {domain} 2>/dev/null && amass subs -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Active Enumeration",
                cmd_template: r#"amass enum -active -d {domain} 2>/dev/null && amass subs -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Brute Force",
                cmd_template: r#"amass enum -brute -d {domain} -w {wordlist} 2>/dev/null && amass subs -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Deep Recon (Passive + Active)",
                cmd_template: r#"amass enum -passive -d {domain} 2>/dev/null && amass enum -active -d {domain} 2>/dev/null && amass subs -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Subdomain Analysis",
                cmd_template: r#"amass subs -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Track New Assets",
                cmd_template: r#"amass track -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Visualization",
                cmd_template: r#"amass viz -d {domain} -o {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Isolated Scan (Clean DB)",
                cmd_template: r#"rm -rf /tmp/amass_{domain} && amass enum -passive -d {domain} -dir /tmp/amass_{domain} 2>/dev/null && amass subs -d {domain} -dir /tmp/amass_{domain} > {output_file} 2>/dev/null && rm -rf /tmp/amass_{domain}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Recon Chain",
                cmd_template: r#"amass enum -passive -d {domain} 2>/dev/null && amass enum -active -d {domain} 2>/dev/null && amass enum -brute -d {domain} -w {wordlist} 2>/dev/null && amass subs -d {domain} > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Intelligence",
                cmd_template: r#"amass enum -passive -d {domain} 2>/dev/null && amass subs -d {domain} -json > {output_file} 2>/dev/null"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "theharvester",
        binary: "theharvester",
        description: "Email harvesting and OSINT gathering from search engines and public sources.",
        modes: &[
            Mode {
                name: "Full Harvest",
                cmd_template: r#"theharvester -d {domain} -b all -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Google Only",
                cmd_template: r#"theharvester -d {domain} -b google -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Bing + LinkedIn",
                cmd_template: r#"theharvester -d {domain} -b bing,linkedin -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Shodan Integration",
                cmd_template: r#"theharvester -d {domain} -b shodan -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Limit Results",
                cmd_template: r#"theharvester -d {domain} -b all -l {limit} -f {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Limit", "limit")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "DNS TLD Expansion",
                cmd_template: r#"theharvester -d {domain} -c -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Virtual Host Check",
                cmd_template: r#"theharvester -d {domain} -v -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "DNS Lookup",
                cmd_template: r#"theharvester -d {domain} -n -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Takeover Check",
                cmd_template: r#"theharvester -d {domain} -t -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Proxy Support",
                cmd_template: r#"theharvester -d {domain} -b all -p {proxy_url} -f {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Proxy Url", "proxy_url")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
        ],
    },
    Tool {
        name: "Naabu",
        binary: "naabu",
        description: "Fast port scanner written in Go with SYN/CONNECT stealth scanning, passive port discovery, and service fingerprinting. No API keys required. Requires root for SYN scans.",
        modes: &[
            Mode {
                name: "Fast Port Scan",
                cmd_template: r#"naabu -host {target} -c 50 -rate 1000 -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Port Scan",
                cmd_template: r#"naabu -host {target} -p - -c 50 -rate 1000 -timeout 30000 -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Top 1000 Ports",
                cmd_template: r#"naabu -host {target} -top-ports 1000 -c 50 -rate 1000 -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Stealth SYN Scan",
                cmd_template: r#"sudo naabu -host {target} -p - -scan-type s -c 100 -rate 5000 -timeout 30000 -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Bulk List Scan",
                cmd_template: r#"naabu -l {file} -c 50 -rate 1000 -json -o {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "ASN Scan",
                cmd_template: r#"naabu -asn {asn} -c 50 -rate 1000 -json -o {output_file}"#,
                inputs: &[InputKind::Custom("ASN", "asn")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Exclude Ports",
                cmd_template: r#"naabu -host {target} -exclude-ports {ports} -c 50 -rate 1000 -json -o {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Exclude Ports", "ports")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Nmap Integration",
                cmd_template: r#"naabu -host {target} -c 50 -rate 1000 -nmap-cli 'nmap -sV -sC -A -oX {output_file}'"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Xml,
                file_ext: "xml",
            },
            Mode {
                name: "Service Discovery",
                cmd_template: r#"naabu -host {target} -p - -c 50 -rate 1000 -timeout 30000 -json -o {output_file} && nmap -sV -sC -p $(cat {output_file} | jq -r '.port' | tr '\n' ',') {target} -oN {output_file}.services"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Passive Port Discovery",
                cmd_template: r#"naabu -host {target} -p - -passive -json -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Recon-ng",
        binary: "recon-cli",
        description: "Modular reconnaissance framework with automated correlation.",
        modes: &[
            Mode {
                name: "Domain Recon",
                cmd_template: r#"recon-ng -r /opt/tsec/scripts/recon-ng-domain.rc > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Contact Harvest",
                cmd_template: r#"recon-cli -w {workspace} -m recon/domains-contacts/whois_pocs -x > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Host Enumeration",
                cmd_template: r#"recon-cli -w {workspace} -m recon/domains-hosts/brute_hosts -x > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Module Search",
                cmd_template: r#"recon-cli -w {workspace} --no-check -C "marketplace search {keyword}" > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace"), InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Module Install",
                cmd_template: r#"recon-cli --no-check -C "marketplace install all" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Netblock Discovery",
                cmd_template: r#"recon-cli -w {workspace} -m recon/domains-hosts/census_api -x > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSL Certificate",
                cmd_template: r#"recon-cli -w {workspace} -m recon/domains-hosts/ssl_san -x > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Report Generation",
                cmd_template: r#"recon-cli -w {workspace} -m reporting/html -o CREATOR=TSEC -o CUSTOMER=TSEC -o FILENAME={output_file} -x"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Credential Search",
                cmd_template: r#"recon-cli -w {workspace} -m recon/domains-credentials/pwnedlist -x > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Recon",
                cmd_template: r#"recon-ng -r /opt/tsec/scripts/recon-ng-full.rc > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Sherlock",
        binary: "sherlock",
        description: "Hunt down usernames across 400+ social networks, forums, and platforms. No API keys required. Useful for OSINT, persona tracking, and social engineering recon.",
        modes: &[
            Mode {
                name: "Single User",
                cmd_template: r#"sherlock {username} --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multiple Users",
                cmd_template: r#"sherlock {username} --output {output_file}"#,
                inputs: &[InputKind::File],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Site Filter",
                cmd_template: r#"sherlock {username} --site instagram,twitter,github,linkedin,facebook,tiktok,youtube,reddit --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CSV Output",
                cmd_template: r#"sherlock {username} --csv --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Csv,
                file_ext: "csv",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"sherlock {username} --json --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Proxy Support",
                cmd_template: r#"sherlock {username} --proxy {proxy_url} --timeout 15 --output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Proxy URL", "proxy_url")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Fast Scan",
                cmd_template: r#"sherlock {username} --timeout 5 --print-found --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Found Only",
                cmd_template: r#"sherlock {username} --print-found --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Browse Results",
                cmd_template: r#"sherlock {username} --browse --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Lethal OSINT Sweep",
                cmd_template: r#"sherlock {username} --csv --json --print-found --timeout 10 --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
        ],
    },
    Tool {
        name: "SpiderFoot",
        binary: "spiderfoot",
        description: "Automated OSINT and threat intelligence platform.",
        modes: &[
            Mode {
                name: "Target Scan",
                cmd_template: r#"spiderfoot -s {target} -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Module List",
                cmd_template: r#"spiderfoot -M > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Specific Modules",
                cmd_template: r#"spiderfoot -s {target} -m sfp_dns,sfp_webframework,sfp_portscan_tcp -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Active Scan",
                cmd_template: r#"spiderfoot -s {target} -n -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "DNS Scan Only",
                cmd_template: r#"spiderfoot -s {target} -t DNS -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Correlation",
                cmd_template: r#"spiderfoot -s {target} -c -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Names Only",
                cmd_template: r#"spiderfoot -s {target} -F -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Use Proxy",
                cmd_template: r#"spiderfoot -s {target} -x {proxy} -o {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Proxy", "proxy")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Exclude Modules",
                cmd_template: r#"spiderfoot -s {target} -m sfp_dns,sfp_subdomain -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Recon",
                cmd_template: r#"spiderfoot -s {target} -a -c -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "OWASP Amass (Intel Mode)",
        binary: "amass",
        description: "Deep intelligence gathering including ASN, routing, and infrastructure mapping.",
        modes: &[
            Mode {
                name: "ASN Lookup",
                cmd_template: r#"amass intel -asn {asn_number} -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn Number", "asn_number")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CIDR Block",
                cmd_template: r#"amass intel -cidr {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Organization Search",
                cmd_template: r#"amass intel -org "{org_name}" -o {output_file}"#,
                inputs: &[InputKind::Custom("Org Name", "org_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Reverse WHOIS",
                cmd_template: r#"amass intel -whois -d {domain} -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP to ASN",
                cmd_template: r#"amass intel -ip -src -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Active Intel",
                cmd_template: r#"amass intel -active -asn {asn} -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn", "asn")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Port Scanning",
                cmd_template: r#"amass intel -p 80,443,8080 -cidr {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IPv6 Support",
                cmd_template: r#"amass intel -ipv6 -cidr {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Data Sources",
                cmd_template: r#"amass intel -src -asn {asn} -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn", "asn")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Infrastructure Map",
                cmd_template: r#"amass intel -active -whois -asn {asn} -cidr {cidr} -org "{org}" -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn", "asn"), InputKind::Ip, InputKind::Custom("Org", "org")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "cloud_enum",
        binary: "cloud_enum.py",
        description: "Multi-cloud OSINT tool for finding public resources in AWS, Azure, and GCP.",
        modes: &[
            Mode {
                name: "AWS Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Azure Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --azure -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "GCP Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --gcp -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "All Clouds",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --all -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "DNS Brute",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --dns-brute -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Mutations",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} -m /opt/tsec/wordlists/cloud_mutations.txt -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "S3 Only",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} -l /opt/tsec/wordlists/s3_regions.txt -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Container Registry",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --container -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Function Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --functions -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Multi-Cloud",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --all -m /opt/tsec/wordlists/cloud_mutations.txt -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Maigret",
        binary: "maigret",
        description: "Advanced username investigation across 3000+ sites with rich data export.",
        modes: &[
            Mode {
                name: "Basic Lookup",
                cmd_template: r#"maigret {username} --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "HTML Report",
                cmd_template: r#"maigret {username} --html {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "CSV Export",
                cmd_template: r#"maigret {username} --csv {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Csv,
                file_ext: "csv",
            },
            Mode {
                name: "Site Filter",
                cmd_template: r#"maigret {username} --site instagram,twitter,reddit --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Tags Filter",
                cmd_template: r#"maigret {username} --tags photo,messaging --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Top Sites Only",
                cmd_template: r#"maigret {username} --top-sites --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Proxy Support",
                cmd_template: r#"maigret {username} --proxy {proxy} --json {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Proxy", "proxy")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Timeout Adjust",
                cmd_template: r#"maigret {username} --timeout 15 --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "No Recheck",
                cmd_template: r#"maigret {username} --no-recheck --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Investigation",
                cmd_template: r#"maigret {username} --all-sites --timeout 20 --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
];
