use crate::tools::types::{Tool, Mode, InputKind, OutputFormat};

pub const TOOLS: &[Tool] = &[
    Tool {
        name: "Subfinder",
        binary: "subfinder",
        description: "Rapid passive subdomain discovery using multiple online sources.",
        modes: &[
            Mode {
                name: "Passive Subdomain Enum",
                cmd_template: r#"subfinder -d {domain} -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "All Sources Enum",
                cmd_template: r#"subfinder -d {domain} -all -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Recursive Subdomain Enum",
                cmd_template: r#"subfinder -d {domain} -recursive -all -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Active + Wildcard Filter",
                cmd_template: r#"subfinder -d {domain} -all -nW -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Specific Sources Enum",
                cmd_template: r#"subfinder -d {domain} -sources shodan,censys,virustotal,crtsh,github -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Source Collection JSON",
                cmd_template: r#"subfinder -d {domain} -all -oJ -cs -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Exclude Sources Enum",
                cmd_template: r#"subfinder -d {domain} -all -es {source} -silent -o {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Source", "source")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP Resolution Output",
                cmd_template: r#"subfinder -d {domain} -all -nW -oI -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Bulk Domain Scan",
                cmd_template: r#"subfinder -dL {domain_list_file} -all -silent -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Pipeline to HTTPX",
                cmd_template: r#"subfinder -d {domain} -all -silent | httpx -silent -sc -title -tech-detect -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Amass",
        binary: "amass",
        description: "Comprehensive DNS enumeration and network mapping with deep correlation.",
        modes: &[
            Mode {
                name: "Passive Enumeration",
                cmd_template: r#"amass enum -passive -d {domain} -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Active Enumeration",
                cmd_template: r#"amass enum -active -d {domain} -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Intel Collection",
                cmd_template: r#"amass intel -d {domain} -whois -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "DNS Enumeration",
                cmd_template: r#"amass enum -d {domain} -src -ip -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "ASN Mapping",
                cmd_template: r#"amass intel -org "{org_name}" -o {output_file}"#,
                inputs: &[InputKind::Custom("Org Name", "org_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Brute Force",
                cmd_template: r#"amass enum -brute -d {domain} -w {wordlist} -o {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Wordlist],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Visual Output",
                cmd_template: r#"amass viz -d3 -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Database Query",
                cmd_template: r#"amass db -names -d {domain} > {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Config-Driven Enum",
                cmd_template: r#"amass enum -config /opt/tsec/configs/amass.ini -d {domain} -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Intelligence",
                cmd_template: r#"amass intel -active -d {domain} -whois -src -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "theHarvester",
        binary: "theHarvester",
        description: "Email harvesting and OSINT gathering from search engines and public sources.",
        modes: &[
            Mode {
                name: "Full Harvest",
                cmd_template: r#"theHarvester -d {domain} -b all -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Google Only",
                cmd_template: r#"theHarvester -d {domain} -b google -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Bing + LinkedIn",
                cmd_template: r#"theHarvester -d {domain} -b bing,linkedin -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Shodan Integration",
                cmd_template: r#"theHarvester -d {domain} -b shodan -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Limit Results",
                cmd_template: r#"theHarvester -d {domain} -b all -l {limit} -f {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Limit", "limit")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "DNS TLD Expansion",
                cmd_template: r#"theHarvester -d {domain} -c -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Virtual Host Check",
                cmd_template: r#"theHarvester -d {domain} -v -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "DNS Lookup",
                cmd_template: r#"theHarvester -d {domain} -n -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Takeover Check",
                cmd_template: r#"theHarvester -d {domain} -t -f {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Proxy Support",
                cmd_template: r#"theHarvester -d {domain} -b all -p {proxy_url} -f {output_file}"#,
                inputs: &[InputKind::Domain, InputKind::Custom("Proxy Url", "proxy_url")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
        ],
    },
    Tool {
        name: "Shodan CLI",
        binary: "shodan",
        description: "Search engine for internet-connected devices and exposed services.",
        modes: &[
            Mode {
                name: "Host Lookup",
                cmd_template: r#"shodan host {ip} > {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Domain Search",
                cmd_template: r#"shodan domain {domain} > {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Search Query",
                cmd_template: r#"shodan search "{query}" --fields ip_str,port,org,hostnames > {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Facet Analysis",
                cmd_template: r#"shodan search "{query}" --facets org,port,os > {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Download Results",
                cmd_template: r#"shodan download {output_file} "{query}""#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Parse Download",
                cmd_template: r#"shodan parse --fields ip_str,port,data {output_file} > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Stats Query",
                cmd_template: r#"shodan stats "{query}" > {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "My IP",
                cmd_template: r#"shodan myip > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Count Results",
                cmd_template: r#"shodan count "{query}" > {output_file}"#,
                inputs: &[InputKind::Custom("Query", "query")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Honeyscore Check",
                cmd_template: r#"shodan honeyscore {ip} > {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Recon-ng",
        binary: "recon-ng",
        description: "Modular reconnaissance framework with automated correlation.",
        modes: &[
            Mode {
                name: "Domain Recon",
                cmd_template: r#"recon-ng -r /opt/tsec/scripts/recon-ng-domain.rc -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Contact Harvest",
                cmd_template: r#"recon-ng -w {workspace} -m recon/domains-contacts/whois_pocs -o {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Host Enumeration",
                cmd_template: r#"recon-ng -w {workspace} -m recon/domains-hosts/brute_hosts -o {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Module Search",
                cmd_template: r#"recon-ng -w {workspace} --no-check -C "marketplace search {keyword}" > {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace"), InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Module Install",
                cmd_template: r#"recon-ng --no-check -C "marketplace install all" > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Netblock Discovery",
                cmd_template: r#"recon-ng -w {workspace} -m recon/domains-hosts/census_api -o {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "SSL Certificate",
                cmd_template: r#"recon-ng -w {workspace} -m recon/domains-hosts/ssl_san -o {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Report Generation",
                cmd_template: r#"recon-ng -w {workspace} -m reporting/html -o {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "Credential Search",
                cmd_template: r#"recon-ng -w {workspace} -m recon/domains-credentials/pwnedlist -o {output_file}"#,
                inputs: &[InputKind::Custom("Workspace", "workspace")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Recon",
                cmd_template: r#"recon-ng -r /opt/tsec/scripts/recon-ng-full.rc -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "Sherlock",
        binary: "sherlock",
        description: "Hunt down usernames across 400+ social networks.",
        modes: &[
            Mode {
                name: "Single User",
                cmd_template: r#"sherlock {username} --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Multiple Users",
                cmd_template: r#"sherlock {user1} {user2} {user3} --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Site Filter",
                cmd_template: r#"sherlock {username} --site instagram,twitter,github --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CSV Output",
                cmd_template: r#"sherlock {username} --csv --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Csv,
                file_ext: "csv",
            },
            Mode {
                name: "JSON Output",
                cmd_template: r#"sherlock {username} --json --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Proxy Support",
                cmd_template: r#"sherlock {username} --proxy {proxy_url} --output {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Proxy Url", "proxy_url")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Timeout Adjust",
                cmd_template: r#"sherlock {username} --timeout 10 --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Found Only",
                cmd_template: r#"sherlock {username} --print-found --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Browse",
                cmd_template: r#"sherlock {username} --browse"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "All Sites + Export",
                cmd_template: r#"sherlock {username} --csv --json --output {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Raw,
                file_ext: "raw",
            },
        ],
    },
    Tool {
        name: "SpiderFoot",
        binary: "spiderfoot",
        description: "Automated OSINT and threat intelligence platform.",
        modes: &[
            Mode {
                name: "Target Scan",
                cmd_template: r#"spiderfoot -s {target} -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Module List",
                cmd_template: r#"spiderfoot -M > {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Specific Modules",
                cmd_template: r#"spiderfoot -s {target} -m sfp_dns,sfp_webframework,sfp_portscan_tcp -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Active Scan",
                cmd_template: r#"spiderfoot -s {target} -n -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "DNS Scan Only",
                cmd_template: r#"spiderfoot -s {target} -t DNS -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Correlation",
                cmd_template: r#"spiderfoot -s {target} -c -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Names Only",
                cmd_template: r#"spiderfoot -s {target} -F -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Use Proxy",
                cmd_template: r#"spiderfoot -s {target} -x {proxy} -o {output_file}"#,
                inputs: &[InputKind::Target, InputKind::Custom("Proxy", "proxy")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Exclude Modules",
                cmd_template: r#"spiderfoot -s {target} -m sfp_dns,sfp_subdomain -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Recon",
                cmd_template: r#"spiderfoot -s {target} -a -c -o {output_file}"#,
                inputs: &[InputKind::Target],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "OWASP Amass (Intel Mode)",
        binary: "amass",
        description: "Deep intelligence gathering including ASN, routing, and infrastructure mapping.",
        modes: &[
            Mode {
                name: "ASN Lookup",
                cmd_template: r#"amass intel -asn {asn_number} -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn Number", "asn_number")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "CIDR Block",
                cmd_template: r#"amass intel -cidr {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Organization Search",
                cmd_template: r#"amass intel -org "{org_name}" -o {output_file}"#,
                inputs: &[InputKind::Custom("Org Name", "org_name")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Reverse WHOIS",
                cmd_template: r#"amass intel -whois -d {domain} -o {output_file}"#,
                inputs: &[InputKind::Domain],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IP to ASN",
                cmd_template: r#"amass intel -ip -src -o {output_file}"#,
                inputs: &[],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Active Intel",
                cmd_template: r#"amass intel -active -asn {asn} -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn", "asn")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Port Scanning",
                cmd_template: r#"amass intel -p 80,443,8080 -cidr {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "IPv6 Support",
                cmd_template: r#"amass intel -ipv6 -cidr {cidr} -o {output_file}"#,
                inputs: &[InputKind::Ip],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Data Sources",
                cmd_template: r#"amass intel -src -asn {asn} -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn", "asn")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
            Mode {
                name: "Full Infrastructure Map",
                cmd_template: r#"amass intel -active -whois -asn {asn} -cidr {cidr} -org "{org}" -o {output_file}"#,
                inputs: &[InputKind::Custom("Asn", "asn"), InputKind::Ip, InputKind::Custom("Org", "org")],
                output_format: OutputFormat::Lines,
                file_ext: "txt",
            },
        ],
    },
    Tool {
        name: "cloud_enum",
        binary: "cloud_enum.py",
        description: "Multi-cloud OSINT tool for finding public resources in AWS, Azure, and GCP.",
        modes: &[
            Mode {
                name: "AWS Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Azure Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --azure -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "GCP Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --gcp -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "All Clouds",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --all -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "DNS Brute",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --dns-brute -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Mutations",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} -m /opt/tsec/wordlists/cloud_mutations.txt -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "S3 Only",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} -l /opt/tsec/wordlists/s3_regions.txt -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Container Registry",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --container -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Function Scan",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --functions -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Multi-Cloud",
                cmd_template: r#"python3 /opt/tsec/tools/cloud_enum/cloud_enum.py --keyword {keyword} --all -m /opt/tsec/wordlists/cloud_mutations.txt -qs --json {output_file}"#,
                inputs: &[InputKind::Custom("Keyword", "keyword")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
    Tool {
        name: "Maigret",
        binary: "maigret",
        description: "Advanced username investigation across 3000+ sites with rich data export.",
        modes: &[
            Mode {
                name: "Basic Lookup",
                cmd_template: r#"maigret {username} --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "HTML Report",
                cmd_template: r#"maigret {username} --html {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Raw,
                file_ext: "html",
            },
            Mode {
                name: "CSV Export",
                cmd_template: r#"maigret {username} --csv {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Csv,
                file_ext: "csv",
            },
            Mode {
                name: "Site Filter",
                cmd_template: r#"maigret {username} --site instagram,twitter,reddit --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Tags Filter",
                cmd_template: r#"maigret {username} --tags photo,messaging --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Top Sites Only",
                cmd_template: r#"maigret {username} --top-sites --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Proxy Support",
                cmd_template: r#"maigret {username} --proxy {proxy} --json {output_file}"#,
                inputs: &[InputKind::Username, InputKind::Custom("Proxy", "proxy")],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Timeout Adjust",
                cmd_template: r#"maigret {username} --timeout 15 --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "No Recheck",
                cmd_template: r#"maigret {username} --no-recheck --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
            Mode {
                name: "Full Investigation",
                cmd_template: r#"maigret {username} --all-sites --timeout 20 --json {output_file}"#,
                inputs: &[InputKind::Username],
                output_format: OutputFormat::Json,
                file_ext: "json",
            },
        ],
    },
];
